"""Checkpointing — saving a calculation folder so its state can be brought back.

**Module:** L1 + L2 (the data model and ``Repo``, the class every surface goes
through).  **Callers:** the ``molbuilder snapshot`` CLI group
(:mod:`molbuilder.cli`) and the HTTP routes in
``molbuilder/web/blueprints/checkpoint.py``; nothing else in the codebase
constructs a ``Repo``, which is what keeps *"nothing is ever saved without you
saying so"* true.

**Contract:** [`execution/checkpointing.md`](?doc=execution/checkpointing.md) —
the goal, the rules (S/I/A/L) and their status.  The **MANIFEST and archive
formats** are [`execution/job-contracts.md`](?doc=execution/job-contracts.md)
§ 6.1; the **guide** (what to type, what the buttons do) is
[`execution/running-a-job.md`](?doc=execution/running-a-job.md) § 6.

Single user, one repository per calculation, no auto-commit.  **No git ever
runs on a compute node** — a generated wrapper contains none, and initialising
is a CLI/UI act (I4; the "wrapper bootstraps git" path was dropped).

Three primitives:
  * Phase 1 init         -- ``Repo.init()``
  * Phase 2 checkpoint   -- ``Repo.checkpoint(message)``
  * Phase 5 restore      -- ``Repo.restore(ref)``

Plus listing + tagging.  Big binaries (``.DM``, ``.HSX``, ``.TSHS``,
``.TBT.AVTRANS_*``) are archived by SHA in ``.binsnapshots/<sha>/``
keyed to their corresponding commit, NOT committed to the git
object database.  Restore copies them back from the archive.

Every git invocation goes through :func:`_run_git` -- argv list,
``cwd`` pinned to the working dir, no shell strings.  Errors raise
:class:`CheckpointError` subclasses with the git stderr verbatim.
"""
from __future__ import annotations

import fnmatch
import hashlib
import os
import re
import shutil
import subprocess
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple


# Big binary patterns (gitignored, archived by SHA on each checkpoint).
# Mirrors the .gitignore policy in docs/execution/running-a-job.md § 6
# --------------------------------------------------------------------- #
#  Classification -- which store a file goes to                         #
#  Contract: checkpointing.md § 3, S1, S1a, S1b, S1c                    #
# --------------------------------------------------------------------- #

#: The only two paths that are never stored (S1).  Not a policy about worth --
#: a store cannot contain itself, and that is the entire list.  Anything else
#: excluded here would be a file in no snapshot, which is S1's losing branch.
NEVER_STORED = (".git", ".binsnapshots")

#: Where the archive lives, one directory per distinct content (§ 3).
ARCHIVE_DIR = ".binsnapshots"

_GITIGNORE_BEGIN = "# === molbuilder checkpoint BEGIN ==="
_GITIGNORE_END = "# === molbuilder checkpoint END ==="


def classification(engine: Optional[str] = None,
                   project_dir=None) -> Dict[str, object]:
    """The size limit and always-large families for this calculation (§ 4).

    Read from molbuilder's own config, never from the folder being saved
    (S1c) -- a per-folder copy is a file somebody can edit between a save and a
    restore, which is exactly the hazard I2c is about.
    """
    from .runtime_config import get_checkpoint
    return get_checkpoint(engine, project_dir)


def is_big(path: Path, size_limit: int, always_large=()) -> bool:
    """Does *path* belong in the archive rather than in git?

    **The size decides (S1b).**  ``always_large`` names families that are
    always over the limit, so those skip the ``stat`` -- a hint that can make a
    save faster and can never make it store less (§ 3).  A file matching no
    hint is measured, which is why an unknown engine is merely slower.
    """
    if any(fnmatch.fnmatch(path.name, pat) for pat in always_large):
        return True
    try:
        return path.stat().st_size > size_limit
    except OSError:
        # Unreadable is not "small": treat it as big so it is archived whole
        # rather than committed, and let the archive's own verify complain.
        return True


def render_gitignore(always_large=()) -> str:
    """The generated ignore block -- ONE source, and it is the classification.

    S1a: what git skips must be exactly what the archive takes, or a file falls
    between them and is in no snapshot at all.  So this renders **nothing but
    archive patterns** plus the archive directory itself; there is no fixed
    tail, because every line in one would be a file excluded by code nobody
    agreed to (S1).

    The size gate cannot be expressed as a gitignore pattern, so files that are
    big *by measurement* are staged out per-save rather than named here.
    """
    lines = [
        _GITIGNORE_BEGIN,
        "# Generated by molbuilder -- do not edit.",
        "# Rewritten from the classification on every save; edits are lost.",
        "# See docs/execution/checkpointing.md S1a.",
        "",
        f"{ARCHIVE_DIR}/",
    ]
    lines += sorted(always_large)
    lines += [_GITIGNORE_END, ""]
    return "\n".join(lines)


def write_gitignore(root: Path, always_large=()) -> None:
    """Write the generated block, preserving anything outside the markers.

    A user's own entries above or below the markers are theirs and are left
    byte-for-byte; everything between them is regenerated, which is what makes
    a hand edit inside detectable by recomputing rather than by a digest
    (I2b).
    """
    gi = root / ".gitignore"
    body = render_gitignore(always_large)
    if not gi.exists():
        gi.write_text(body, encoding="utf-8")
        return
    text = gi.read_text(encoding="utf-8")
    b, e = text.find(_GITIGNORE_BEGIN), text.find(_GITIGNORE_END)
    if b != -1 and e > b:
        text = text[:b] + body + text[e + len(_GITIGNORE_END):].lstrip("\n")
    elif text.strip():
        text = text.rstrip("\n") + "\n\n" + body
    else:
        text = body
    gi.write_text(text, encoding="utf-8")


def gitignore_is_current(root: Path, always_large=()) -> bool:
    """Does the marked block match what regenerating it would produce (I2b)?

    `.gitignore` records a *derivation*, so the derivation is the check: a
    stored digest could not catch an edit that rode into a save, because the
    save would hash whatever it found and bless it.
    """
    gi = root / ".gitignore"
    if not gi.is_file():
        return False
    text = gi.read_text(encoding="utf-8")
    b, e = text.find(_GITIGNORE_BEGIN), text.find(_GITIGNORE_END)
    if b == -1 or e <= b:
        return False
    return text[b:e + len(_GITIGNORE_END)] == render_gitignore(
        always_large).rstrip("\n")


# File markers indicating a directory is itself a working dir (must not
# be subsumed by a parent's checkpoint repo per P5 lowest-directory rule).
_NESTED_WORKING_DIR_MARKERS = (".fdf", ".py", ".run.sh")


# --------------------------------------------------------------------- #
#  Exceptions                                                           #
# --------------------------------------------------------------------- #


class CheckpointError(Exception):
    """Base class for run-checkpoints errors."""


class GitNotInstalledError(CheckpointError):
    """``git`` is not on PATH."""


class DirtyWorkingTreeError(CheckpointError):
    """Operation refuses to proceed on a dirty working tree."""


class NoSuchRefError(CheckpointError):
    """The named ref / tag / branch / SHA does not resolve."""


class NestedRepoRefusedError(CheckpointError):
    """Init refused because the directory contains nested working dirs
    (per P5 lowest-directory rule)."""


# --------------------------------------------------------------------- #
#  Data model                                                           #
# --------------------------------------------------------------------- #


@dataclass(frozen=True)
class State:
    """One saved snapshot of the whole folder (§ 5).

    ``id`` is git's own commit hash: permanent, never reused, and nothing
    assigns or stores it.  ``archive`` is the sha256 of that state's MANIFEST —
    a *name* and a *proof* in one value (I2b), present on every state including
    those that archived nothing.
    """
    id:          str
    note:        str
    parent:      Optional[str]      # the state this one came from
    at:          str                # ISO-8601 UTC
    archive:     Optional[str] = None   # Manifest-SHA256; None if damaged
    calculation: Optional[str] = None   # which calculation this belongs to
    tags:        Tuple[str, ...] = ()

    @property
    def short(self) -> str:
        return self.id[:7]


@dataclass(frozen=True)
class Tag:
    """A name you gave a state so you could find it again (§ 5, L4).

    Nothing creates one on your behalf; the namespace is yours alone.
    """
    name:  str
    state: str
    note:  str


@dataclass(frozen=True)
class FolderStatus:
    """Where the folder stands, and what is unsaved (§ 5, A5).

    ``standing_at`` is the one state the folder is currently at.  Everything
    else is measured **against that state and never against the newest one** —
    which is why going back does not make the whole folder read as modified.

    The three lists are A5's three shapes, and all three are lost when a
    restore makes the folder equal its target.
    """
    path:        str
    initialized: bool
    standing_at: Optional[str] = None
    changed:      Tuple[str, ...] = ()
    added:        Tuple[str, ...] = ()
    deleted:      Tuple[str, ...] = ()
    ignore_edited: bool = False     # the generated block was hand-edited (I2b)

    @property
    def clean(self) -> bool:
        return not (self.changed or self.added or self.deleted)

    def unsaved(self) -> Tuple[str, ...]:
        """Everything at risk, in one sorted list — what A5's warning names."""
        return tuple(sorted(set(self.changed) | set(self.added)
                            | set(self.deleted)))


# --------------------------------------------------------------------- #
#  Internals                                                            #
# --------------------------------------------------------------------- #


def _run_git(argv: List[str], cwd: str, *,
             check: bool = True) -> subprocess.CompletedProcess:
    """Run ``git argv`` in ``cwd``; return CompletedProcess.

    Sets a molbuilder git identity in the environment so a checkpoint works on
    a machine where the user never ran ``git config --global user.email``.
    ``setdefault``, so a real identity already present is left alone.
    """
    env = os.environ.copy()
    env.setdefault("GIT_AUTHOR_NAME",     "molbuilder")
    env.setdefault("GIT_AUTHOR_EMAIL",
                   f"molbuilder@{os.uname().nodename}")
    env.setdefault("GIT_COMMITTER_NAME",  env["GIT_AUTHOR_NAME"])
    env.setdefault("GIT_COMMITTER_EMAIL", env["GIT_AUTHOR_EMAIL"])
    try:
        return subprocess.run(
            ["git", *argv],
            cwd=cwd,
            env=env,
            capture_output=True,
            text=True,
            check=check,
        )
    except FileNotFoundError as e:
        raise GitNotInstalledError(
            "git is not on PATH.  molbuilder requires git ≥ 2.20; "
            "install via your distro's package manager OR activate the "
            "molbuilder conda env (`conda activate molbuilder-host` -- "
            "every molbuilder env ships git as a conda_packages entry)."
        ) from e
    except subprocess.CalledProcessError as e:
        # Re-raise with stderr surfaced so callers can wrap.
        msg = (e.stderr or e.stdout or str(e)).strip()
        raise CheckpointError(
            f"git {' '.join(argv[:3])}... failed: {msg}"
        ) from e


#: A directory holding one of these declares itself **one unit of work whose
#: subdirectories are its own parts** -- a staged calculation's stages, a
#: job-set's job directories, a benchmark's trials.  Each is already an entry in
#: the persisted-artifact registry (job-contracts.md § 6.1), so this reuses the
#: system's existing self-description instead of inventing a marker file.
_BUNDLE_DESCRIPTORS = ("task.json", "job-set.json", "bench-manifest.json")


def _is_bundle_root(path: Path) -> bool:
    """Does ``path`` declare itself the root of one multi-directory unit of
    work?  See :data:`_BUNDLE_DESCRIPTORS`."""
    return any((path / name).is_file() for name in _BUNDLE_DESCRIPTORS)


def _scan_subtree(path: Path) -> Tuple[List[str], List[str]]:
    """One pruned walk returning ``(working_dirs, git_repos)`` beneath
    ``path``, both as relative POSIX-ish paths.

    * ``working_dirs`` -- subdirectories holding a working-dir marker
      (``.fdf`` / ``.py`` / ``.run.sh``).  Symlinked decks count, because a
      prepped job directory links its deck in rather than copying it.
    * ``git_repos`` -- subdirectories that are themselves repositories.  The
      walk does **not** descend into one: what is inside another repository is
      that repository's business.

    Dot-directories are skipped entirely.  Before, only ``.git`` and
    ``.binsnapshots`` were -- so a ``.venv/`` beside a run (full of ``.py``)
    read as a nested working directory and blocked ``init`` for a reason that
    had nothing to do with calculations.
    """
    working: List[str] = []
    repos: List[str] = []
    stack: List[Path] = [path]
    while stack:
        try:
            entries = sorted(stack.pop().iterdir())
        except OSError:                       # unreadable dir: not our problem
            continue
        for entry in entries:
            if entry.is_symlink() or not entry.is_dir():
                continue
            if entry.name.startswith("."):    # .git, .binsnapshots, .venv, …
                continue
            rel = str(entry.relative_to(path))
            if (entry / ".git").is_dir():
                repos.append(rel)
                continue                      # never descend into another repo
            if any(f.is_file() and f.name.endswith(_NESTED_WORKING_DIR_MARKERS)
                   for f in entry.iterdir()):
                working.append(rel)
            stack.append(entry)
    return sorted(working), sorted(repos)


#: Directories the archive walk never descends into.  ``.binsnapshots`` would
#: make the archive archive itself; ``.git`` holds packfiles that are git's own
#: business.  Any other dot-directory is tooling scratch, not run state.
def archive_key(root: Path, path: Path) -> str:
    """A file's key inside an archive: its path relative to the folder root.

    Repo-relative rather than a bare basename, so one archive can hold a `.DM`
    from every stage without them colliding (L2).
    """
    return path.relative_to(root).as_posix()


def walk_files(root: Path):
    """Every regular file that belongs in a store (S1).

    Skips only :data:`NEVER_STORED` — the two stores themselves — and symlinks.
    **No other exclusion**: "no category of file is exempt", and a walk with a
    private skip list is a walk that agrees with itself about files nobody
    stores.

    Symlinks are outside S1 by its own wording: a link has no content of its
    own, the real file is stored once wherever it lives, and recreating the
    layout is what a restore does anyway.
    """
    for path in sorted(root.rglob("*")):
        rel = path.relative_to(root)
        # Any component, not just the first: a stray `sub/.git` is somebody
        # else's repository and is no more ours to store than our own.  The
        # walk and the key check must exclude the same set, or a file the walk
        # collects is a file the MANIFEST refuses and the save dies on.
        if any(part in NEVER_STORED for part in rel.parts):
            continue
        if path.is_symlink() or not path.is_file():
            continue
        yield path


def split_by_store(root: Path, size_limit: int, always_large=()):
    """Partition the folder into ``(big, small)`` — the archive's and git's.

    Every regular file lands in exactly one list, which is S1 stated as code.
    """
    big, small = [], []
    for path in walk_files(root):
        (big if is_big(path, size_limit, always_large) else small).append(path)
    return big, small


# --------------------------------------------------------------------- #
#  MANIFEST + the content-addressed archive                             #
#  Format: job-contracts.md § 6.1.  Naming: checkpointing.md § 3.       #
# --------------------------------------------------------------------- #

#: I2b: a record named so nobody mistakes it for a setting.  Chosen once, here;
#: nothing has to read an older name.
MANIFEST_NAME = "MANIFEST.do_not_edit"

_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
_SIZE_RE   = re.compile(r"^(0|[1-9][0-9]*)$")
_SEP       = "\t"

#: sha256 of b"" -- the archive every state with no big files points at.
EMPTY_MANIFEST_DIGEST = hashlib.sha256(b"").hexdigest()


def _bad(where: str, why: str) -> "CheckpointError":
    return CheckpointError(f"malformed MANIFEST in {where}: {why} "
                           f"(job-contracts.md § 6.1).")


def format_manifest(entries: Sequence[Tuple[str, int, str]]) -> bytes:
    """Render entries as the canonical MANIFEST (job-contracts.md § 6.1).

    One set of files has exactly **one** possible MANIFEST, byte for byte,
    because its sha256 is the archive's directory name (§ 3).  Sorting and the
    single spelling of every field are what make that true, so this refuses to
    emit anything it could not read back.
    """
    seen = set()
    lines = []
    for sha256, size, key in sorted(entries, key=lambda e: e[2]):
        if not _SHA256_RE.match(sha256):
            raise CheckpointError(
                f"cannot write MANIFEST: {sha256!r} is not 64 lowercase hex "
                f"characters (job-contracts.md § 6.1).")
        if not isinstance(size, int) or isinstance(size, bool) or size < 0:
            raise CheckpointError(
                f"cannot write MANIFEST: size {size!r} for {key!r} is not a "
                f"non-negative integer (job-contracts.md § 6.1).")
        _check_key(key, "cannot write MANIFEST")
        if key in seen:
            raise CheckpointError(
                f"cannot write MANIFEST: {key!r} appears more than once; a key "
                f"names one file (job-contracts.md § 6.1).")
        seen.add(key)
        lines.append(f"{sha256}{_SEP}{size}{_SEP}{key}")
    return ("".join(ln + "\n" for ln in lines)).encode("ascii")


def _check_key(key: str, prefix: str) -> None:
    """A key must never steer a restore out of the folder (job-contracts § 6.1)."""
    if not key:
        raise CheckpointError(f"{prefix}: an empty key is not a path.")
    if any(ord(c) < 0x20 or ord(c) > 0x7E for c in key):
        raise CheckpointError(
            f"{prefix}: {key!r} contains non-printable or non-ASCII "
            f"characters (job-contracts.md § 6.1).")
    if key.startswith("/") or "\\" in key:
        raise CheckpointError(
            f"{prefix}: {key!r} must be a repo-relative POSIX path "
            f"(job-contracts.md § 6.1).")
    for part in key.split("/"):
        if part in ("", ".", ".."):
            raise CheckpointError(
                f"{prefix}: {key!r} has an empty or dot component, which "
                f"could steer a restore outside the folder "
                f"(job-contracts.md § 6.1).")
        if part in NEVER_STORED:
            raise CheckpointError(
                f"{prefix}: {key!r} names a store ({part}), and a restore "
                f"writing there would corrupt the history it is restoring "
                f"from (job-contracts.md § 6.1).")


def parse_manifest(raw: bytes, where: str) -> Dict[str, Tuple[str, int]]:
    """Strict reader.  Returns ``{key: (sha256, size)}``.

    Refuses everything that is not exactly the canonical form — no field-count
    fallback, no header, no comments, no BOM tolerance.  A reader that guesses
    is a reader that restores the wrong bytes, and under content addressing a
    reader that tolerates two spellings cannot agree with the writer about the
    archive's name.
    """
    if raw == b"":
        return {}                       # legal: this state archived nothing
    if raw.startswith(b"\xef\xbb\xbf"):
        raise _bad(where, "starts with a UTF-8 BOM; the format is plain ASCII")
    if b"\r" in raw:
        raise _bad(where, "contains CR bytes; line endings are LF only")
    if not raw.endswith(b"\n"):
        raise _bad(where, "missing the final newline")
    try:
        text = raw.decode("ascii")
    except UnicodeDecodeError as e:
        raise _bad(where, f"non-ASCII byte at offset {e.start}") from e

    out: Dict[str, Tuple[str, int]] = {}
    keys: List[str] = []
    for idx, line in enumerate(text.split("\n")[:-1], start=1):
        if not line:
            raise _bad(where, f"line {idx} is blank")
        parts = line.split(_SEP)
        if len(parts) != 3:
            raise _bad(where, f"line {idx} has {len(parts)} tab-separated "
                              f"field(s); the format is exactly three")
        sha256, size_s, key = parts
        if not _SHA256_RE.match(sha256):
            raise _bad(where, f"line {idx}: {sha256!r} is not 64 lowercase "
                              f"hex characters")
        if not _SIZE_RE.match(size_s):
            raise _bad(where, f"line {idx}: {size_s!r} is not a decimal "
                              f"integer without leading zeros")
        _check_key(key, f"malformed MANIFEST in {where}, line {idx}")
        if key in out:
            raise _bad(where, f"line {idx}: {key!r} appears more than once")
        out[key] = (sha256, int(size_s))
        keys.append(key)
    if keys != sorted(keys):
        raise _bad(where, "lines are not sorted by key; two writers would "
                          "otherwise produce two different archives")
    return out


def manifest_digest(raw: bytes) -> str:
    """The archive's name: the sha256 of its own MANIFEST (§ 3).

    One value that locates the archive, proves it, and makes it impossible to
    modify without becoming a different archive.
    """
    return hashlib.sha256(raw).hexdigest()


def archive_dir(root: Path, digest: str) -> Path:
    """``<root>/.binsnapshots/<digest>/`` — named by content, not by state."""
    if not _SHA256_RE.match(digest):
        raise CheckpointError(
            f"archive name {digest!r} is not a sha256 digest; an archive is "
            f"named by its MANIFEST's content (checkpointing.md § 3).")
    return root / ARCHIVE_DIR / digest


def _atomic_write_bytes(target: Path, data: bytes) -> None:
    """Write via a sibling temp + ``os.replace`` so readers never see a partial."""
    tmp = target.with_name(target.name + ".tmp")
    tmp.write_bytes(data)
    os.replace(tmp, target)


# --------------------------------------------------------------------- #
#  Publishing an archive (A1, I1, § 6)                                  #
# --------------------------------------------------------------------- #


def _existing_by_sha(root: Path) -> Dict[str, Path]:
    """Every already-archived file, indexed by content.

    Serves the *Disk cost* property (§ 12): identical content is stored once,
    so a second save of an unchanged 2 GB binary costs a directory entry.
    """
    index: Dict[str, Path] = {}
    base = root / ARCHIVE_DIR
    if not base.is_dir():
        return index
    for adir in sorted(base.iterdir()):
        man = adir / MANIFEST_NAME
        if not (adir.is_dir() and man.is_file()):
            continue
        try:
            entries = parse_manifest(man.read_bytes(), str(adir))
        except CheckpointError:
            continue                     # a damaged archive indexes nothing
        for key, (sha256, _size) in entries.items():
            index.setdefault(sha256, adir / key)
    return index


def publish_archive(root: Path, big: Sequence[Path]) -> str:
    """Write the archive for *big* and return its digest (§ 6).

    Build in a ``.tmp``, hash the source, copy, **re-hash the copy** and
    compare, write the MANIFEST, then publish at the digest — *create if
    absent, never overwrite* (A1).  An archive at a given name always holds the
    same content, so there is nothing to replace and nothing to move aside.

    Re-hashing the copy is not belt-and-braces: if the MANIFEST's checksum came
    from the copy alone, a copy corrupted on the way to disk would be
    *self-consistent* and would verify against its own bad checksum forever.
    """
    entries: List[Tuple[str, int, str]] = []
    for src in big:
        entries.append((hashlib.sha256(src.read_bytes()).hexdigest(),
                        src.stat().st_size, archive_key(root, src)))
    raw = format_manifest(entries)
    digest = manifest_digest(raw)
    final = archive_dir(root, digest)
    if (final / MANIFEST_NAME).is_file():
        return digest                    # already published; identical by name

    tmp = final.with_name(digest + ".tmp")
    if tmp.exists():
        shutil.rmtree(tmp)
    tmp.mkdir(parents=True)
    index = _existing_by_sha(root)
    try:
        for sha256, _size, key in entries:
            src = root / key
            dst = tmp / key
            dst.parent.mkdir(parents=True, exist_ok=True)
            reuse = index.get(sha256)
            if reuse is not None and reuse.is_file():
                try:
                    os.link(reuse, dst)
                    continue              # same inode: already verified once
                except OSError:
                    pass                  # cross-device or unsupported: copy
            shutil.copy2(src, dst)
            if hashlib.sha256(dst.read_bytes()).hexdigest() != sha256:
                raise CheckpointError(
                    f"archive copy of {key!r} is corrupt: it does not match "
                    f"the source it was copied from.  Refusing to publish an "
                    f"archive that would verify against its own bad checksum "
                    f"(checkpointing.md § 6).")
        _atomic_write_bytes(tmp / MANIFEST_NAME, raw)
        try:
            os.replace(tmp, final)
        except OSError:
            if (final / MANIFEST_NAME).is_file():
                shutil.rmtree(tmp, ignore_errors=True)   # someone else won
            else:
                raise
    except BaseException:
        shutil.rmtree(tmp, ignore_errors=True)
        raise
    return digest


def verify_archive(root: Path, digest: str) -> Dict[str, Tuple[str, int]]:
    """Check an archive against its MANIFEST, touching nothing (I2).

    Existence, size and sha256 for every entry.  Returns the expected map so a
    caller can act on what it just verified rather than reading it twice.
    """
    adir = archive_dir(root, digest)
    man = adir / MANIFEST_NAME
    if not man.is_file():
        raise CheckpointError(
            f"archive {digest[:12]}… is missing: no {MANIFEST_NAME} at {adir}. "
            f"The state that names it recorded this archive, so it was lost "
            f"(checkpointing.md I2b).")
    raw = man.read_bytes()
    if manifest_digest(raw) != digest:
        raise CheckpointError(
            f"archive {digest[:12]}…: its {MANIFEST_NAME} does not hash to the "
            f"name it is stored under.  The record was modified "
            f"(checkpointing.md I2b).")
    expected = parse_manifest(raw, str(adir))
    for key, (sha256, size) in expected.items():
        src = adir / key
        if not src.is_file():
            raise CheckpointError(
                f"archive {digest[:12]}…: {MANIFEST_NAME} lists {key!r} but "
                f"the file is missing; refusing to restore (I2).")
        if src.stat().st_size != size:
            raise CheckpointError(
                f"archive {digest[:12]}…: {key!r} is {src.stat().st_size} "
                f"bytes, the record says {size}; refusing to restore (I2).")
        if hashlib.sha256(src.read_bytes()).hexdigest() != sha256:
            raise CheckpointError(
                f"archive {digest[:12]}…: {key!r} does not match its recorded "
                f"sha256; refusing to restore (I2).")
    return expected


# --------------------------------------------------------------------- #
#  The trailer -- one value that is both pointer and proof (I2b)        #
# --------------------------------------------------------------------- #

TRAILER = "Manifest-SHA256"
CALC_TRAILER = "Calculation"
_TRAILERS = (TRAILER, CALC_TRAILER)

#: L3: used verbatim in every state's message and never rewritten, so a name
#: needing repair is refused rather than quietly fixed -- silently normalising
#: an id would decouple the history's name from the folder's.
_CALC_NAME_RE = re.compile(r"^[A-Za-z0-9_-]+$")


def check_calculation_name(name: str) -> str:
    """L3: refuse a name that would have to be repaired to be used."""
    if not _CALC_NAME_RE.match(name or ""):
        raise CheckpointError(
            f"calculation name {name!r} is not [A-Za-z0-9_-]+.  It is written "
            f"verbatim into every state and never rewritten, so a name that "
            f"needs repair is refused rather than quietly changed -- fixing it "
            f"silently would decouple this history's name from the folder's "
            f"(checkpointing.md L3).")
    return name


def message_with_trailers(note: str, digest: str, calculation: str) -> str:
    """A state's message: your note, then what the state is *of* and *holds*.

    Both trailers are appended by the SAVE, never by a note helper: a save may
    carry any note at all, and hanging them off a helper would let every save
    that skipped it ship unanchored and unnamed (I2b, L3).
    """
    return (f"{note.rstrip()}\n\n"
            f"{CALC_TRAILER}: {calculation}\n"
            f"{TRAILER}: {digest}\n")


def _trailer_value(message: str, key: str) -> Optional[str]:
    for line in message.splitlines():
        if line.startswith(key + ":"):
            return line.split(":", 1)[1].strip() or None
    return None


def trailer_of(message: str) -> Optional[str]:
    """The archive digest a state names, or None if it carries no anchor."""
    value = _trailer_value(message, TRAILER)
    return value if value and _SHA256_RE.match(value) else None


def calculation_of(message: str) -> Optional[str]:
    """Which calculation this state belongs to (L3).

    Why a state carries it at all: a folder can be copied to a cluster or
    opened a year later, and a history whose states say only "stage 2
    converged" cannot say which calculation that was.
    """
    return _trailer_value(message, CALC_TRAILER)


def note_of(message: str) -> str:
    """The note, without the trailers -- what a person reads in a list."""
    return "\n".join(
        ln for ln in message.splitlines()
        if not any(ln.startswith(k + ":") for k in _TRAILERS)).strip()


# --------------------------------------------------------------------- #
#  Repo -- the class every surface goes through (§ 15)                  #
# --------------------------------------------------------------------- #

#: One ref per state, so **every state stays reachable forever** whatever else
#: is restored afterwards (A6).  Nothing depends on where HEAD points, which is
#: what lets a restore move the folder without any state becoming unreferenced.
_STATE_REF = "refs/molbuilder/state/"


class Repo:
    """A calculation folder under checkpointing.

    **Contract:** `execution/checkpointing.md`.  The vocabulary is the
    contract's: a **state** is a saved snapshot of the whole folder, a **tag**
    is a name you gave one, and the folder always **stands at** exactly one
    state (§ 5).  There are no branches and no lines; a fork is what happens
    when you save from a restored state (§ 7.1).
    """

    def __init__(self, path: str) -> None:
        self.path = str(path)
        self.root = Path(path)

    # -- setup ---------------------------------------------------- #

    @property
    def initialized(self) -> bool:
        return (self.root / ".git").is_dir()

    def _require_init(self) -> None:
        if not self.initialized:
            raise CheckpointError(
                f"{self.path} is not a checkpoint folder; run "
                f"`molbuilder snapshot init` first.")

    def init(self, engine: Optional[str] = None,
             note: str = "set up",
             calculation: Optional[str] = None) -> "State":
        """Make this folder a checkpoint folder and save its first state.

        One repository per calculation (L1).  A folder whose subdirectories are
        working dirs is accepted only when this folder declares them one
        calculation by carrying its description; without one, several
        independent calculations would share a history and rewind together.
        """
        if self.initialized:
            return self.standing_at()
        working, inner = _scan_subtree(self.root)
        if inner:
            raise NestedRepoRefusedError(
                f"{self.path}: cannot init -- these subdirectories are already "
                f"checkpoint folders: {inner}.  A history inside a history "
                f"cannot be restored consistently (L1).")
        if working and not _is_bundle_root(self.root):
            raise NestedRepoRefusedError(
                f"{self.path}: cannot init -- nested working dirs present: "
                f"{working}, and nothing here says they belong to one "
                f"calculation.  Its root should carry the description that "
                f"says so ({', '.join(_BUNDLE_DESCRIPTORS)}) (L1).")
        name = check_calculation_name(calculation or self.root.name)
        _run_git(["init", "-q"], cwd=self.path)
        _run_git(["config", "molbuilder.calculation", name], cwd=self.path)
        if engine:
            _run_git(["config", "molbuilder.engine", engine], cwd=self.path)
        write_gitignore(self.root, self._classification()["always_large"])
        return self.save(note)

    def _engine(self) -> Optional[str]:
        """Which config entry this folder's saves use (§ 4).

        Kept in the repository's own git config -- inside ``.git/``, which is
        never stored (S1) and is not a file anybody edits by hand.  It is
        **not** a second classification: it names which entry to read, while
        the patterns and the size limit stay in molbuilder.json (S1c).

        Losing it is safe by design -- an unnamed engine resolves to
        ``generic``, which measures every file and is "always correct and
        merely measures more".  It is persisted so that property costs a stat
        sweep only when nobody said what the engine was, rather than always.
        """
        if not self.initialized:
            return None
        out = _run_git(["config", "--get", "molbuilder.engine"],
                       cwd=self.path, check=False).stdout.strip()
        return out or None

    def calculation(self) -> str:
        """Which calculation this folder's history belongs to (L3).

        Defaults to the folder's own name, which is what a person recognises,
        and is fixed at init: it is written verbatim into every state, so
        changing it later would make one history claim two names.
        """
        self._require_init()
        out = _run_git(["config", "--get", "molbuilder.calculation"],
                       cwd=self.path, check=False).stdout.strip()
        return out or self.root.name

    def _classification(self) -> Dict[str, object]:
        return classification(self._engine(), self.root)

    # -- states ---------------------------------------------------- #

    def _state_from(self, sha: str) -> "State":
        out = _run_git(["show", "-s", "--format=%H%x00%P%x00%aI%x00%B", sha],
                       cwd=self.path).stdout
        sha_full, parents, at, message = out.split("\x00", 3)
        parent = parents.split()[0] if parents.strip() else None
        return State(id=sha_full.strip(), note=note_of(message),
                     parent=parent, at=at.strip(),
                     archive=trailer_of(message),
                     calculation=calculation_of(message),
                     tags=tuple(self._tag_names_at(sha_full.strip())))

    def _tag_names_at(self, sha: str) -> List[str]:
        out = _run_git(["tag", "--points-at", sha], cwd=self.path,
                       check=False).stdout
        return sorted(n for n in out.split() if n)

    def standing_at(self) -> Optional["State"]:
        """The one state the folder is currently at (§ 5).

        Set by `init`, by `save`, and by `restore`.  Everything `status` reports
        is measured against it and never against the newest state, which is why
        going back does not make the whole folder read as modified.
        """
        self._require_init()
        r = _run_git(["rev-parse", "HEAD"], cwd=self.path, check=False)
        sha = r.stdout.strip()
        return self._state_from(sha) if r.returncode == 0 and sha else None

    def states(self, limit: Optional[int] = None) -> List["State"]:
        """Every state, newest first.  Nothing is ever removed (A6)."""
        self._require_init()
        # Topological order, not date order.  Several states can share a
        # second -- a scripted sweep saves faster than the clock ticks -- and a
        # tie there would print a child above its own parent.  Topology cannot
        # tie: a state always follows the state it came from.
        out = _run_git(["rev-list", "--topo-order",
                        "--glob=" + _STATE_REF + "*"],
                       cwd=self.path, check=False).stdout
        shas = [s for s in out.split() if s]
        if limit is not None:
            shas = shas[:int(limit)]
        return [self._state_from(s) for s in shas]

    def resolve(self, ref: str) -> str:
        """A state id or a tag -> the state's id.  One kind of argument."""
        self._require_init()
        r = _run_git(["rev-parse", "--verify", "--quiet", f"{ref}^{{commit}}"],
                     cwd=self.path, check=False)
        sha = r.stdout.strip()
        if r.returncode != 0 or not sha:
            raise NoSuchRefError(
                f"{ref!r} does not name a state or a tag in {self.path}.")
        return sha

    # -- what is unsaved ------------------------------------------- #

    def status(self, deep: bool = False) -> "FolderStatus":
        """Where the folder stands, and what differs from it (§ 5, A5).

        Three shapes -- changed, added, deleted -- covering text and big files
        alike.  Big files are gitignored, so git cannot see them; they are
        compared against the standing state's MANIFEST, which is the record
        that says what that state held (I2c).

        **Two depths, and the difference is who pays for exactness.**

        ``deep=False`` (the default) is the *display*: size and timestamp only,
        never content.  It answers the sidebar on every directory-enter and the
        CLI's ``list``, where reading a 2 GB density matrix to draw a badge is a
        cost the answer does not earn.  Its one blind spot is a file rewritten
        to the same size within the same second as the save -- and being wrong
        there costs nothing, because **nothing is moving**: it is a sentence on
        a screen, corrected the next time anything real happens.

        ``deep=True`` hashes.  It is what runs before an operation that changes
        the folder, where being wrong costs data rather than a sentence, and it
        is what a Refresh control asks for when somebody wants certainty now.
        """
        if not self.initialized:
            return FolderStatus(path=self.path, initialized=False)
        here = self.standing_at()
        edited = not gitignore_is_current(
            self.root, self._classification()["always_large"])
        changed, added, deleted = set(), set(), set()

        cls = self._classification()
        big, _small = split_by_store(self.root, int(cls["size_limit_bytes"]),
                                     cls["always_large"])
        on_disk = {archive_key(self.root, p): p for p in big}

        expected: Dict[str, Tuple[str, int]] = {}
        _archived_keys: set = set()
        if here is not None and here.archive:
            try:
                man = archive_dir(self.root, here.archive) / MANIFEST_NAME
                if man.is_file():
                    expected = parse_manifest(man.read_bytes(), str(man))
                    _archived_keys = set(expected)
            except CheckpointError:
                raise CheckpointError(
                    "cannot say what is unsaved: the archive for the state "
                    "this folder stands at is unreadable.  Nothing is safe "
                    "to overwrite until that is resolved (I2b).")
        # git's view of these files is noise and must be dropped.  A file that
        # is big by *size* rather than by *name* cannot be named in .gitignore,
        # so git sees it as untracked and would report it as added on every
        # status -- including immediately after it was saved.  The archive is
        # their record, and the comparison below is the only thing entitled to
        # speak about them (I2c).
        for line in _run_git(["status", "--porcelain", "-uall"],
                             cwd=self.path).stdout.splitlines():
            if not line.strip():
                continue
            code, name = line[:2], line[3:].strip()
            if name in on_disk or name in _archived_keys:
                continue
            if code == "??" or code[0] == "A":
                added.add(name)
            elif "D" in code:
                deleted.add(name)
            else:
                changed.add(name)

        # I2c: what is unsaved is measured against the standing state's
        # MANIFEST -- the record of what that state HELD -- unioned with what
        # the classification says is big NOW, which is the only way a
        # brand-new big file is noticed.  Iterating the classification alone
        # would report a file as *deleted* the moment it stopped matching an
        # always-large pattern, while it sat untouched on disk.
        # Cheap first, exact only when it has to be.  This runs on every
        # directory-enter in the sidebar (docs/web/projects.md), and a folder
        # holding a 2 GB density matrix must not be read end-to-end to answer
        # "is anything unsaved".  A different SIZE is already an answer; only a
        # same-size file that was touched after the state was saved needs
        # hashing, and an untouched one cannot have changed.
        saved_at = _epoch_of(here.at) if here is not None else None
        for key in set(expected) | set(on_disk):
            path = self.root / key
            if not path.is_file():
                deleted.add(key)
                continue
            want = expected.get(key)
            if want is None:
                added.add(key)
                continue
            stat = path.stat()
            if stat.st_size != want[1]:
                changed.add(key)              # a different size is an answer
                continue
            if not deep and saved_at is not None:
                # ONE SECOND of tolerance, and it is resolution rather than
                # slack.  A state's timestamp is whole seconds; a file's is
                # not.  Save a file at 12:00:00.3 and the state records
                # 12:00:00, so a bare `>` calls the file newer than the state
                # that just saved it -- the folder would read unsaved the
                # instant after a save, which is the normal flow and not a
                # corner case.
                #
                # What this cannot see is a same-size rewrite inside that
                # second.  Accepted deliberately: nothing moves on a status
                # call, so being briefly wrong costs a sentence and not a byte,
                # and every operation that CAN lose something checks content.
                if stat.st_mtime > saved_at + 1:
                    changed.add(key)
                continue
            # Falls through to the exact comparison when asked for it -- and
            # also when the state's timestamp is unreadable, because "cannot
            # rule it out cheaply" must mean *check*, not *assume changed*.
            if hashlib.sha256(path.read_bytes()).hexdigest() != want[0]:
                changed.add(key)

        return FolderStatus(
            path=self.path, initialized=True,
            standing_at=here.id if here else None,
            changed=tuple(sorted(changed - added - deleted)),
            added=tuple(sorted(added)), deleted=tuple(sorted(deleted)),
            ignore_edited=edited)

    # -- save ------------------------------------------------------ #

    def save(self, note: str) -> Optional["State"]:
        """Save the folder as a new state.  The note is required (L3).

        The new state's parent is **where the folder stood**, then the folder
        stands at the new state.  That is the whole of the branching mechanism
        (§ 7.1): you never declare a fork, you save from where you are.

        Returns ``None`` when nothing changed.
        """
        self._require_init()
        if not (note or "").strip():
            raise CheckpointError(
                "a state needs a note saying what happened and what you were "
                "about to do -- it is the only thing that answers the question "
                "you bring to a history a month later, and it is not "
                "defaulted (checkpointing.md L3).")
        cls = self._classification()
        always = cls["always_large"]
        # I2b: `.gitignore` records a DERIVATION, so the derivation is the
        # check -- regenerating it every save is what makes a hand edit
        # harmless rather than a file silently dropped from every store.
        write_gitignore(self.root, always)
        big, _small = split_by_store(self.root,
                                     int(cls["size_limit_bytes"]), always)

        # The size gate cannot be a gitignore pattern, so a file that is big by
        # MEASUREMENT is staged out here -- and a file that stopped being big
        # is staged back in.  That is S7: a file that changes category leaves
        # the store it came from, which becomes ordinary once the gate is a
        # size, because files grow.
        _run_git(["add", "-A"], cwd=self.path)
        for path in big:
            _run_git(["rm", "--cached", "-q", "--ignore-unmatch", "--",
                      archive_key(self.root, path)], cwd=self.path,
                     check=False)

        digest = publish_archive(self.root, big)
        here = self.standing_at()
        staged = _run_git(["diff", "--cached", "--name-only"],
                          cwd=self.path, check=False).stdout.strip()
        if not staged and here is not None and here.archive == digest:
            return None                   # nothing changed, in either store

        _run_git(["commit", "-q", "--allow-empty", "-m",
                  message_with_trailers(note, digest, self.calculation())],
                 cwd=self.path)
        sha = _run_git(["rev-parse", "HEAD"], cwd=self.path).stdout.strip()
        _run_git(["update-ref", _STATE_REF + sha, sha], cwd=self.path)
        return self._state_from(sha)


    # -- restore ---------------------------------------------------- #

    def restore(self, ref: str, force: bool = False) -> "State":
        """Make the folder equal *ref* exactly (A5), or refuse (A2, A4).

        Order is the rule.  The two refusals come first because they are about
        the **target** -- an unknown state or an archive that does not verify
        means the operation cannot happen at all, and nobody should be asked to
        accept a loss for an operation that then fails for an unrelated reason.
        The question about unsaved work comes last, immediately before the
        first byte moves.

        A restore is whole or it does not happen (A4): text and big files are
        one state, and returning half of one save and half of another produces
        a folder no save ever held.
        """
        self._require_init()
        sha = self.resolve(ref)                       # refusal 1: unknown
        target = self._state_from(sha)
        if not target.archive:
            raise CheckpointError(
                f"state {target.short} carries no archive digest, so what it "
                f"held cannot be checked.  Refusing to restore from a record "
                f"that cannot be verified (I2b).")
        expected = verify_archive(self.root, target.archive)   # refusal 2

        # DEEP, always.  This is the moment the folder is about to change, so
        # the question "what will be lost" is answered by content and not by a
        # timestamp -- the cheap read exists for drawing a badge, not for
        # deciding what to destroy.
        status = self.status(deep=True)               # the question, last
        if not status.clean and not force:
            raise DirtyWorkingTreeError(
                "this folder has work that is not saved, and restoring will "
                "lose it:\n"
                + _describe(status)
                + "\n\nSave it first with `molbuilder snapshot save -m \"…\"`, "
                  "or pass --force to accept the loss.")

        # --- from here on the folder is being changed --------------- #
        _run_git(["checkout", "--force", "--detach", sha], cwd=self.path)
        _run_git(["clean", "-fdq"], cwd=self.path)

        # Everything the target did not hold is removed -- not a loss, and not
        # warned about (A5): those files are still in the state that holds
        # them, and leaving a stage 2 .DM in a folder claiming to be stage 1 is
        # exactly the file a later run picks up unasked.
        #
        # What belongs here is decided by TWO RECORDS AND NO CONFIGURATION
        # (I2a): git says which text the target held, the MANIFEST says which
        # big files it held, and anything else is a leftover.  Deriving the set
        # from the classification instead would make a restore mean different
        # things before and after a config edit -- and `git clean` alone cannot
        # do it, because a file matching an ignore pattern is invisible to it.
        tracked = set(_run_git(["ls-files"], cwd=self.path).stdout.split())
        for path in walk_files(self.root):
            key = archive_key(self.root, path)
            if key not in tracked and key not in expected:
                path.unlink()

        adir = archive_dir(self.root, target.archive)
        for key in sorted(expected):
            dst = self.root / key
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(adir / key, dst)
        return target

    # -- tags ------------------------------------------------------ #

    def tag(self, name: str, note: str, at: Optional[str] = None) -> "Tag":
        """Give a state a name so you can find it again (§ 5, L4)."""
        self._require_init()
        if not (name or "").strip():
            raise CheckpointError("a tag needs a name.")
        if not (note or "").strip():
            raise CheckpointError(
                "a tag needs a note saying why this state is worth returning "
                "to (L3).")
        sha = self.resolve(at) if at else self.resolve("HEAD")
        _run_git(["tag", "-a", name, sha, "-m", note], cwd=self.path)
        return Tag(name=name, state=sha, note=note)

    def tags(self) -> List["Tag"]:
        self._require_init()
        # ``*objectname`` is the commit an annotated tag points AT; plain
        # ``objectname`` would be the tag object itself, which is not a state.
        #
        # Space-separated with the free text LAST, not %x00-separated:
        # `for-each-ref` does not interpret %xNN escapes, so a NUL format
        # emits the four literal characters and the whole line parses as one
        # field.  A tag name and a hash cannot contain spaces; a note can, so
        # it goes last and the split is bounded.
        out = _run_git(["for-each-ref",
                        "--format=%(refname:short) %(*objectname) "
                        "%(contents:subject)", "refs/tags"],
                       cwd=self.path, check=False).stdout
        found = []
        for line in out.splitlines():
            if not line.strip():
                continue
            parts = (line.split(" ", 2) + ["", ""])[:3]
            name, state, subject = parts
            found.append(Tag(name=name, state=state or self.resolve(name),
                             note=subject))
        return sorted(found, key=lambda t: t.name)


def _epoch_of(iso: str) -> Optional[float]:
    """An ISO-8601 timestamp as epoch seconds, or None if unreadable.

    Unreadable means "cannot rule the file out cheaply", and the caller then
    hashes -- slower, never wrong.
    """
    try:
        return datetime.fromisoformat(iso).timestamp()
    except (ValueError, TypeError):
        return None


def _describe(status: "FolderStatus") -> str:
    """A5's three shapes, named -- never a count.

    "3 unsaved files" tells nobody anything; `01_coarse/job.DM` tells them the
    density matrix is what they are about to walk away from.
    """
    parts = []
    for label, names in (("changed", status.changed),
                         ("added", status.added),
                         ("deleted", status.deleted)):
        for name in names:
            parts.append(f"  {label:>7}  {name}")
    return "\n".join(parts)
