"""molwatch parser registry.

Adding support for a new output format is two steps:
  1. drop a new ``foo.py`` module here that defines a ``FooParser``
     subclass of ``TrajectoryParser`` (see base.py for the contract);
  2. import it below and append the class to ``PARSERS``.

The Flask app calls :func:`detect_parser` on every load and never
references a specific parser by name.
"""

from __future__ import annotations

import os
from typing import Any, Dict, List, Type

from ..frame import Frame, Trajectory
from .base import TrajectoryParser
from .molwatch_log import MolwatchLogParser
from .siesta import SiestaParser
from .pyscf import PySCFParser


# Order matters: the first parser whose ``can_parse(path)`` returns
# True wins.  Put more-specific parsers (with stricter format markers)
# first so they aren't shadowed by a permissive one.
#
# MolwatchLogParser goes first: its header marker
# ``# molwatch trajectory log`` is unambiguous and won't false-match
# any engine-native format.  This is the preferred path for any run
# generated by molbuilder -- a single self-contained file with the
# whole trajectory + per-cycle SCF data, no sibling-file discovery
# needed.  SIESTA and raw PySCF parsers remain as fallbacks for runs
# that weren't generated through molbuilder.
PARSERS: List[Type[TrajectoryParser]] = [
    MolwatchLogParser,
    SiestaParser,
    PySCFParser,
]


class UnknownFormatError(ValueError):
    """No registered parser claims to understand this file."""


def detect_parser(path: str) -> Type[TrajectoryParser]:
    """Return the first parser class whose ``can_parse(path)`` is True.

    Raises :class:`UnknownFormatError` if no parser matches; the error
    message lists every registered format with its hint, plus a
    targeted suggestion for the most common foot-gun (uploading the
    PySCF .log instead of the geomeTRIC _optim.xyz).
    """
    for cls in PARSERS:
        try:
            if cls.can_parse(path):
                return cls
        except Exception:
            # A parser's sniffer should never raise -- but if it does,
            # don't let one buggy parser take down the dispatch.
            continue

    base = os.path.basename(path)
    lines = [f"No registered parser knows how to handle {base!r}."]
    lines.append("Supported formats:")
    for c in PARSERS:
        suffix = f" -- {c.hint}" if c.hint else ""
        lines.append(f"  * {c.label}{suffix}")

    # Filename-based hints for the two most common mistakes.  These
    # are pure heuristics: we only trigger them on filename patterns
    # that are unambiguous about user intent, so a real misfire is
    # cheap.
    lower = base.lower()

    # 1. .fdf is the SIESTA INPUT, not its output.  SIESTA writes
    #    output to wherever stdout was redirected (typically
    #    siesta.out / <label>.out).  Easy mistake because the .fdf
    #    is the file molbuilder hands the user.
    if lower.endswith(".fdf"):
        stem = base[:-len(".fdf")]
        lines.append("")
        lines.append(
            f"That looks like a SIESTA INPUT file (.fdf), not the "
            f"output.  SIESTA writes its output to wherever you "
            f"redirected stdout, typically:"
        )
        lines.append(f"    mpirun siesta < {base} > {stem}.out")
        lines.append(
            f"Load '{stem}.out' (or whatever you redirected to) "
            f"instead.  If you generated this run with molbuilder, "
            f"there's also a '{stem}.molwatch.log' alongside it that "
            f"shows the initial geometry immediately."
        )

    # 2. PySCF .log is the runtime log; the parser wants the
    #    geomeTRIC trajectory <job>_geom_optim.xyz instead.  Stem-
    #    match so we don't spam the suggestion for SIESTA users
    #    (whose main output ALSO often ends in .log).
    elif (lower.endswith(".log") and
          ("pyscf" in lower or "_relax" in lower or "geom" in lower)):
        stem = base
        for suffix in (".log", "_geom.log", "_pyscf.log"):
            if stem.endswith(suffix):
                stem = stem[: -len(suffix)]
                break
        lines.append("")
        lines.append(
            f"Looks like a PySCF run -- load the geomeTRIC trajectory "
            f"'{stem}_geom_optim.xyz' instead.  If you generated this "
            f"run with molbuilder, '{stem}.molwatch.log' is the "
            f"preferred single-file input."
        )

    # 3. Generic catch-all hint pointing at the debug guide.  Always
    #    safe to include and steers the user to the docs that explain
    #    what each parser actually checks.
    else:
        lines.append("")
        lines.append(
            "See README.md ('How auto-detection decides') or "
            "docs/spec/parsers.md ('Detection order and debugging') "
            "for the per-parser detection rules and a debug checklist."
        )

    raise UnknownFormatError("\n".join(lines))


def parser_summary() -> List[dict]:
    """Lightweight metadata used by the /api/formats endpoint."""
    return [
        {"name": c.name, "label": c.label, "hint": c.hint}
        for c in PARSERS
    ]


def trajectory_to_legacy_dict(traj: Trajectory) -> Dict[str, Any]:
    """Adapter: build the molwatch v1 JSON dict from a Trajectory.

    The watch web layer (``molbuilder/web/blueprints/watch.py``) calls
    this to keep returning the same JSON shape the existing 3Dmol.js
    client consumes.  Phase 3 will redesign the JSON to surface
    Trajectory directly; this adapter goes away then.

    Output shape:

      {
        "frames":      [ [[el, x, y, z], ...], ... ],
        "energies":    [ float | null, ... ],
        "max_forces":  [ float | null, ... ],
        "forces":      [ [[fx, fy, fz], ...] | [], ... ],
        "iterations":  [ int, ... ],
        "lattice":     [[ax, ay, az], ...] | null,
        "scf_history": [ [ {cycle, energy, delta_E, ...}, ... ], ... ],
        "source_format": "siesta" | "pyscf" | "molwatch" | ...,
      }

    None / empty-list mapping (matches the legacy parsers' output):
      Frame.forces      = None  ->  forces      = []
      Frame.scf_history = None  ->  scf_history = []
      Trajectory.lattice = None ->  lattice     = null
      Frame.energy / max_force unset stays as None -> JSON null.
    """
    out_frames:     List[List[List[Any]]] = []
    out_energies:   List[Any] = []
    out_max_forces: List[Any] = []
    out_forces:     List[List[List[float]]] = []
    out_iterations: List[int] = []
    out_scf:        List[List[Dict[str, Any]]] = []

    for f in traj.frames:
        atom_rows: List[List[Any]] = []
        for el, pos in zip(f.structure.elements, f.structure.positions):
            atom_rows.append([el, float(pos[0]), float(pos[1]), float(pos[2])])
        out_frames.append(atom_rows)

        out_energies.append(f.energy)
        out_max_forces.append(f.max_force)
        if f.forces is not None:
            out_forces.append([[float(v) for v in row] for row in f.forces])
        else:
            out_forces.append([])
        out_iterations.append(f.step_index)
        out_scf.append(f.scf_history if f.scf_history is not None else [])

    # Legacy shape quirk: when no parser tracks SCF data for ANY
    # frame (PySCF .log absent, SIESTA had no `scf:` lines), the
    # original parsers returned a top-level empty list -- not
    # [[], [], ...].  We collapse to that shape only when EVERY
    # frame's scf_history is None (the parser-says-no-scf-data
    # signal); a frame with `scf_history=[]` is intentional (e.g. a
    # molwatch preview block carries an empty SCF section) and
    # stays as [] in the output.
    if traj.frames and all(f.scf_history is None for f in traj.frames):
        out_scf = []

    if traj.lattice is not None:
        lattice_out: Any = [list(row) for row in traj.lattice.tolist()]
    else:
        lattice_out = None

    return {
        "frames":        out_frames,
        "lattice":       lattice_out,
        "iterations":    out_iterations,
        "energies":      out_energies,
        "max_forces":    out_max_forces,
        "forces":        out_forces,
        "scf_history":   out_scf,
        "source_format": traj.source_format,
    }


__all__ = [
    "PARSERS",
    "Frame",
    "Trajectory",
    "TrajectoryParser",
    "UnknownFormatError",
    "detect_parser",
    "parser_summary",
    "trajectory_to_legacy_dict",
]
