"""Trajectory parser registry.

Adding support for a new output format is two steps:
  1. drop a new ``foo.py`` module here that defines a ``FooParser``
     subclass of ``TrajectoryParser`` (see base.py for the contract);
  2. import it below and append the class to ``PARSERS``.

The Flask app calls :func:`detect_parser` on every load and never
references a specific parser by name.
"""

from __future__ import annotations

import os
from typing import Any, Dict, List, Type

from ..frame import Frame, Trajectory
from .base import TrajectoryParser
from .molwatch_log import MolwatchLogParser
from .siesta import SiestaParser
from .pyscf import PySCFParser


# Order matters: the first parser whose ``can_parse(path)`` returns
# True wins.  Put more-specific parsers (with stricter format markers)
# first so they aren't shadowed by a permissive one.
#
# MolwatchLogParser goes first: its header marker
# ``# molwatch trajectory log`` is unambiguous and won't false-match
# any engine-native format.  This is the preferred path for any run
# generated by molbuilder -- a single self-contained file with the
# whole trajectory + per-cycle SCF data, no sibling-file discovery
# needed.  SIESTA and raw PySCF parsers remain as fallbacks for runs
# that weren't generated through molbuilder.
PARSERS: List[Type[TrajectoryParser]] = [
    MolwatchLogParser,
    SiestaParser,
    PySCFParser,
]


class UnknownFormatError(ValueError):
    """No registered parser claims to understand this file."""


def detect_parser(path: str) -> Type[TrajectoryParser]:
    """Return the first parser class whose ``can_parse(path)`` is True.

    Raises :class:`UnknownFormatError` if no parser matches; the error
    message lists every registered format with its hint, plus a
    targeted suggestion for the most common foot-gun (uploading the
    PySCF .log instead of the geomeTRIC _optim.xyz).
    """
    for cls in PARSERS:
        try:
            if cls.can_parse(path):
                return cls
        except Exception:
            # A parser's sniffer should never raise -- but if it does,
            # don't let one buggy parser take down the dispatch.
            continue

    base = os.path.basename(path)
    lines = [f"No registered parser knows how to handle {base!r}."]
    lines.append("Supported formats:")
    for c in PARSERS:
        suffix = f" -- {c.hint}" if c.hint else ""
        lines.append(f"  * {c.label}{suffix}")

    # Filename-based hints for the two most common mistakes.  These
    # are pure heuristics: we only trigger them on filename patterns
    # that are unambiguous about user intent, so a real misfire is
    # cheap.
    lower = base.lower()

    # 1. .fdf is the SIESTA INPUT, not its output.  SIESTA writes
    #    output to wherever stdout was redirected (typically
    #    siesta.out / <label>.out).  Easy mistake because the .fdf
    #    is the file molbuilder hands the user.
    if lower.endswith(".fdf"):
        stem = base[:-len(".fdf")]
        lines.append("")
        lines.append(
            "That looks like a SIESTA INPUT file (.fdf), not the "
            "output.  SIESTA writes its output to wherever you "
            "redirected stdout, typically:"
        )
        lines.append(f"    mpirun siesta < {base} > {stem}.out")
        lines.append(
            f"Load '{stem}.out' (or whatever you redirected to) "
            f"instead.  If you generated this run with molbuilder, "
            f"there's also a '{stem}.molwatch.log' alongside it that "
            f"shows the initial geometry immediately."
        )

    # 2. PySCF .log is the runtime log; the parser wants the
    #    geomeTRIC trajectory <job>_geom_optim.xyz instead.  Stem-
    #    match so we don't spam the suggestion for SIESTA users
    #    (whose main output ALSO often ends in .log).
    elif (lower.endswith(".log") and
          ("pyscf" in lower or "_relax" in lower or "geom" in lower)):
        stem = base
        for suffix in (".log", "_geom.log", "_pyscf.log"):
            if stem.endswith(suffix):
                stem = stem[: -len(suffix)]
                break
        lines.append("")
        lines.append(
            f"Looks like a PySCF run -- load the geomeTRIC trajectory "
            f"'{stem}_geom_optim.xyz' instead.  If you generated this "
            f"run with molbuilder, '{stem}.molwatch.log' is the "
            f"preferred single-file input."
        )

    # 3. Generic catch-all hint pointing at the debug guide.  Always
    #    safe to include and steers the user to the docs that explain
    #    what each parser actually checks.
    else:
        lines.append("")
        lines.append(
            "See README.md ('How auto-detection decides') or "
            "docs/types/parsers.md ('Detection order and debugging') "
            "for the per-parser detection rules and a debug checklist."
        )

    raise UnknownFormatError("\n".join(lines))


def _nan_to_none(obj: Any) -> Any:
    """Recursively replace NaN floats with ``None`` for JSON safety.

    The JSON spec doesn't allow ``NaN`` / ``Infinity`` tokens; Python's
    ``json.dumps`` emits them anyway (``allow_nan=True`` is the
    default), but the BROWSER's strict ``r.json()`` / ``JSON.parse``
    rejects them and the fetch throws -- silently blanking the
    Results-tab view.

    NaN reaches the trajectory dict primarily from
    ``_parse_fortran_float`` (Fortran fixed-width overflow on a
    divergent SCF cycle), but any future numeric path that surfaces
    NaN ends up here too.  Replacing with ``None`` (which serialises
    as ``null``) lets the frontend treat the overflow column as
    "value missing" -- exactly the diagnostic the NaN signal was
    meant to convey, and Plotly renders the gap in the trace.

    Walks dicts and lists in-place semantics (returns a new structure
    so callers don't get surprise mutations of their inputs).
    """
    if isinstance(obj, float):
        # math.isnan would import math just for this; the NaN-only
        # check ``obj != obj`` is a stdlib-free idiom for the same
        # thing.  Infinity passes through (json.dumps emits
        # ``Infinity`` similarly out-of-spec; if a future code path
        # produces it we should sweep it too, but no real engine
        # output does today).
        return None if obj != obj else obj
    if isinstance(obj, dict):
        return {k: _nan_to_none(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_nan_to_none(v) for v in obj]
    if isinstance(obj, tuple):
        return tuple(_nan_to_none(v) for v in obj)
    return obj


def trajectory_to_legacy_dict(traj: Trajectory) -> Dict[str, Any]:
    """Adapter: build the molwatch v1 JSON dict from a Trajectory.

    The watch web layer (``molbuilder/web/blueprints/watch.py``) calls
    this to keep returning the same JSON shape the existing 3Dmol.js
    client consumes.

    Output shape:

      {
        "frames":      [ [[el, x, y, z], ...], ... ],
        "energies":    [ float | null, ... ],
        "max_forces":  [ float | null, ... ],
        "forces":      [ [[fx, fy, fz], ...] | [], ... ],
        "iterations":  [ int, ... ],
        "lattice":     [[ax, ay, az], ...] | null,
        "scf_history": [ [ {cycle, energy, delta_E, ...}, ... ], ... ],
        "source_format": "siesta" | "pyscf" | "molwatch" | ...,
      }

    None / empty-list mapping (matches the legacy parsers' output):
      Frame.forces      = None  ->  forces      = []
      Frame.scf_history = None  ->  scf_history = []
      Trajectory.lattice = None ->  lattice     = null
      Frame.energy / max_force unset stays as None -> JSON null.
    """
    out_frames:     List[List[List[Any]]] = []
    out_energies:   List[Any] = []
    out_max_forces: List[Any] = []
    out_max_forces_constrained: List[Any] = []
    out_forces:     List[List[List[float]]] = []
    out_iterations: List[int] = []
    out_scf:        List[List[Dict[str, Any]]] = []
    out_wall_times: List[Any] = []

    for f in traj.frames:
        atom_rows: List[List[Any]] = []
        for el, pos in zip(f.structure.elements, f.structure.positions):
            atom_rows.append([el, float(pos[0]), float(pos[1]), float(pos[2])])
        out_frames.append(atom_rows)

        out_energies.append(f.energy)
        out_max_forces.append(f.max_force)
        out_max_forces_constrained.append(
            getattr(f, "max_force_constrained", None))
        if f.forces is not None:
            out_forces.append([[float(v) for v in row] for row in f.forces])
        else:
            out_forces.append([])
        out_iterations.append(f.step_index)
        out_scf.append(f.scf_history if f.scf_history is not None else [])
        out_wall_times.append(f.wall_time)

    # Legacy shape quirk: when no parser tracks SCF data for ANY
    # frame (PySCF .log absent, SIESTA had no `scf:` lines), the
    # original parsers returned a top-level empty list -- not
    # [[], [], ...].  We collapse to that shape only when EVERY
    # frame's scf_history is None (the parser-says-no-scf-data
    # signal); a frame with `scf_history=[]` is intentional (e.g. a
    # molwatch preview block carries an empty SCF section) and
    # stays as [] in the output.
    if traj.frames and all(f.scf_history is None for f in traj.frames):
        out_scf = []

    if traj.lattice is not None:
        lattice_out: Any = [list(row) for row in traj.lattice.tolist()]
    else:
        lattice_out = None

    # 2026-06-12: ``max_forces_constrained`` collapses to a single
    # top-level empty list when NO frame had a constrained value
    # (the typical case: no frozen atoms anywhere in the run).  Saves
    # a few KB on big trajectories AND signals "no constraints in
    # this run" to consumers without them having to scan the array
    # for non-null entries.  A frame WITH a constrained value
    # stretches the array to full length, with None for any frame
    # that lacks one (the parser only sees the constrained line
    # after the unconstrained one in the same step, so missing
    # entries usually mean a partial parse).
    if all(v is None for v in out_max_forces_constrained):
        out_max_forces_constrained = []

    # Browser-side ``r.json()`` is strict-spec: ``NaN`` and ``Infinity``
    # are not legal JSON tokens.  Python's ``json.dumps`` will happily
    # emit ``NaN`` (default ``allow_nan=True``); when the response
    # reaches the browser, the fetch throws SyntaxError and the
    # Results-tab trajectory plot renders blank.
    #
    # ``_nan_to_none`` walks the output and replaces every NaN with
    # ``None`` (→ JSON ``null``).  NaN reaches us mostly via
    # ``_parse_fortran_float`` (SIESTA fixed-width overflow on
    # divergent SCF cycles), but any other code path that surfaces
    # NaN -- now or in the future -- gets sanitised here too, at the
    # single adapter that all watch / results endpoints flow through.
    # Plotly renders ``null`` as a gap in the line; that gap IS the
    # divergence diagnostic (per the 2026-06-14 BDT-stage-2 report).
    out_scf = _nan_to_none(out_scf)
    out_energies = _nan_to_none(out_energies)
    out_max_forces = _nan_to_none(out_max_forces)
    out_max_forces_constrained = _nan_to_none(out_max_forces_constrained)
    out_forces = _nan_to_none(out_forces)
    out_frames = _nan_to_none(out_frames)
    lattice_out = _nan_to_none(lattice_out)

    return {
        "frames":        out_frames,
        "lattice":       lattice_out,
        "iterations":    out_iterations,
        "energies":      out_energies,
        "max_forces":    out_max_forces,
        "max_forces_constrained": out_max_forces_constrained,
        "forces":        out_forces,
        "scf_history":   out_scf,
        "wall_times":    out_wall_times,
        "source_format": traj.source_format,
        # Run-state markers from end-of-run detection.  See
        # Trajectory.run_state docstring.
        "run_state":     traj.run_state,
        "error_message": traj.error_message,
        # Runtime facts (CPU / memory / GPU / host) captured by the
        # parser from the file's header.  Same keys for every engine
        # so /results' inspector renders uniformly.  Empty dict for
        # logs from before the header emission landed.
        "runtime_info":  dict(getattr(traj, "runtime_info", {}) or {}),
        # Level-3 fail-soft warnings (2026-05-28).  Per-line parser
        # issues that did NOT abort the parse but the user should see.
        # The Results tab renders this list in a collapsible panel
        # so a stale dHmax value or a tight-packed SIESTA SCF line is
        # surfaced (not silently swallowed).  Each entry has
        # ``line_no``, ``snippet``, ``error``, ``category``.
        "parse_warnings": [
            {
                "line_no":  w.line_no,
                "snippet":  w.snippet,
                "error":    w.error,
                "category": w.category,
            }
            for w in getattr(traj, "parse_warnings", []) or []
        ],
    }


__all__ = [
    "PARSERS",
    "Frame",
    "Trajectory",
    "TrajectoryParser",
    "UnknownFormatError",
    "detect_parser",
    "trajectory_to_legacy_dict",
]
