"""molwatch unified-log FileParser.

Absorbed from the legacy
``molbuilder.parsers.molwatch_log.MolwatchLogParser``; that package was
deleted 2026-06-21 and this is the only molwatch reader (provenance:
`docs/archive/old_docs/protocols/parse-module.md` § 8).

molwatch is the preferred path for any run generated by molbuilder
— one self-contained file with the whole trajectory + per-cycle SCF
data, no sibling-file discovery needed.  Registered first in the
engine registry so its unambiguous header marker (``# molwatch
trajectory log``) wins over engine-native sniffers.

Format reference (.molwatch.log):

    # molwatch trajectory log
    # engine: pyscf
    # runtime.<key>: <value>           (optional, repeated)
    # convergence.<key>: <value>       (optional, repeated)
    ==== molwatch step 0 begin ====
    step_index: 0
    n_atoms: 3
    coordinates (Ang):
       O   0.00 0.00 0.00
       ...
    energy (eV): -76.12
    forces (eV/Ang):
       ...
    max_force (eV/Ang): 0.0024
    scf_history begin
    # cycle energy delta_E gnorm ddm
       1   -76.00   0.00   5e-2   1e-1
    scf_history end
    wall_time: 1718000000.123        (epoch -> Frame.wall_clock_s)
    ==== molwatch step 0 end ====
    ...
    # concluded: success                (optional footer)
    # error: <message>                  (optional footer)

Robustness:
  * Header line in the first 5 lines is the format-detection marker.
  * Torn final block (``begin`` w/o matching ``end``) is dropped.
  * Missing residual values printed as ``None`` round-trip to None.
"""

from __future__ import annotations

from pathlib import Path
from typing import List

import numpy as np

from molbuilder.frame import Frame, Trajectory
from molbuilder.parse.base import FileParser
from molbuilder.parse.types import TrajectoryResult
from molbuilder.structure import Structure

from ._helpers import wrap_trajectory
from ._sidecar import read_frozen_atoms


# THE GRAMMAR IS `molwatch_grammar`'s -- header, step block and footer, each
# line with its one reader -- which this parser, the PySCF parser, the ending
# scan and the monitor all read.  It stood here until 2026-09-26; it moved so
# the monitor, which runs where numpy does not, reads a PySCF run's progress
# with the same lines (`execution/run-reports.md` § 2.3).
from . import molwatch_grammar as _MG
from .molwatch_reader import MolwatchReader


def _parse_molwatch_log(path: str) -> Trajectory:
    """Parse a .molwatch.log into a Trajectory.

    Driver maintains two compiled rule tables (out-block / in-block)
    and flips between them on block_begin / block_end transitions.
    See module docstring for the file format.
    """
    from molbuilder.parse._log import ParseLogger
    with ParseLogger(path, parser_name="molwatch") as _scan_log:
        return _parse_molwatch_log_impl(path, _scan_log)


def _parse_molwatch_log_impl(path: str, _scan_log) -> Trajectory:
    """The log through the one reading pass (`molwatch_reader`), and a Frame
    per step block it read -- the arrays are this module's alone."""
    reader = MolwatchReader()
    with open(path, "r", errors="replace") as fh:
        for line_no, raw in enumerate(fh, start=1):
            reader.feed(raw.rstrip("\n"), line_no)
    read = reader.finish()
    runtime_info = read["runtime_info"]
    frames: List[Frame] = []
    for block in read["blocks"]:
        coords = block["coords"]
        frames.append(Frame(
            structure   = Structure(
                elements=[row[0] for row in coords],
                positions=np.array([row[1:4] for row in coords], dtype=float)),
            step_index  = block["index"],
            energy      = block["energy"],
            forces      = (np.asarray(block["forces"], dtype=float)
                           if block["forces"] else None),
            max_force   = block["max_force"],
            # Always a list (possibly empty) -- the .molwatch.log format
            # always carries an scf_history block per step.  None is
            # reserved for parsers with no SCF data source.
            scf_history  = list(block["scf_history"]),
            # The emitter stamps its own time.time(), so this log DOES carry
            # a time of day (parse.md § 2a).  ``elapsed_s`` is left unset:
            # deriving it from the epoch series has exactly one home, and it
            # is not here (P-T3 -- trajectory_result_to_legacy_dict does).
            wall_clock_s = block["wall_clock_s"],
        ))
    # Surface the .molstruct.json sidecar's frozen_atoms list (same contract
    # as the SIESTA + PySCF parsers) for the "Hide frozen atoms" overlay.
    frozen = sorted(read_frozen_atoms(path))
    if frozen:
        runtime_info["frozen_atoms"] = frozen

    _scan_log.info(
        f"parsed {len(frames)} frames, run_state={read['run_state']}")
    if read["error_message"]:
        _scan_log.error(read["error_message"])
    return Trajectory(
        source_format = read["engine"],
        frames        = frames,
        lattice       = None,
        run_state     = read["run_state"],
        error_message = read["error_message"],
        runtime_info  = runtime_info,
    )


class MolwatchLogParser:
    """Body parser for ``.molwatch.log`` files.  Returns legacy
    :class:`Trajectory`; use :class:`MolwatchLogFileParser` for a
    typed :class:`TrajectoryResult`.

    Mirrors the legacy ``MolwatchLogParser`` API: ``can_parse(path)
    -> bool`` + ``parse(path) -> Trajectory``, plus ``name`` /
    ``label`` / ``hint`` class attributes so introspecting callers
    see the same surface as the legacy class."""

    name  = "molwatch"
    label = "molwatch unified log (.molwatch.log)"
    hint  = ("the unified per-step log emitted by molbuilder-generated "
             "PySCF scripts (e.g. <job>.molwatch.log)")

    @classmethod
    def can_parse(cls, path):
        return MolwatchLogFileParser.can_parse(Path(path))

    parse = staticmethod(_parse_molwatch_log)


class MolwatchLogFileParser(FileParser):
    """Parse a ``.molwatch.log`` unified trajectory file."""

    name   = "molwatch"
    label  = "molwatch unified log (.molwatch.log)"
    hint   = ("the unified per-step log emitted by molbuilder-generated "
              "PySCF scripts (e.g. <job>.molwatch.log)")
    output = TrajectoryResult

    @classmethod
    def can_parse(cls, path: Path) -> bool:
        try:
            with open(path, "r", errors="replace") as fh:
                head = [next(fh, "") for _ in range(5)]
        except OSError:
            return False
        return any(_MG.HEADER.match(line) for line in head)

    @classmethod
    def parse(cls, path: Path) -> TrajectoryResult:
        traj = _parse_molwatch_log(str(path))
        return wrap_trajectory(traj, cls.name, path)
