"""molwatch unified-log FileParser.

Phase C of parse-module.md migration: thin wrapper over the
legacy
:class:`molbuilder.parsers.molwatch_log.MolwatchLogParser`.  This
is the preferred path for any run generated by molbuilder — one
self-contained file with the whole trajectory + per-cycle SCF
data, no sibling-file discovery needed.

Registered first in the engine registry so its unambiguous
header marker (``# molwatch trajectory log``) wins over engine-
native sniffers.
"""

from __future__ import annotations

from pathlib import Path

from molbuilder.parse.base import FileParser
from molbuilder.parse.types import TrajectoryResult
from molbuilder.parsers.molwatch_log import MolwatchLogParser as _LegacyMolwatchLogParser

from ._helpers import wrap_trajectory


class MolwatchLogFileParser(FileParser):
    """Parse a ``.molwatch.log`` unified trajectory file."""

    name   = "molwatch-log"
    label  = _LegacyMolwatchLogParser.label
    hint   = _LegacyMolwatchLogParser.hint
    output = TrajectoryResult

    @classmethod
    def can_parse(cls, path: Path) -> bool:
        return _LegacyMolwatchLogParser.can_parse(str(path))

    @classmethod
    def parse(cls, path: Path) -> TrajectoryResult:
        traj = _LegacyMolwatchLogParser.parse(str(path))
        return wrap_trajectory(traj, cls.name, path)
