"""3-run orchestration — derive the relax / electrode / device bundle
from one labeled device, with the file hand-offs wired automatically.

What this solves (transiesta-workflow.md § 6.4)
================================================

A TranSIESTA conductance number is the product of THREE coupled SIESTA
runs (§ 1):

    relax  ─┐
            ├─▶  device (NEGF)  ─▶  tbtrans  ─▶  T(E), G₀
  electrode ┤
    leads  ─┘

Today the user runs each by hand and copies files between them — the
relaxed coordinates into the device, and each ``electrode.TSHS`` into the
device's ``TS.Elec`` reference under the right name.  Every manual copy is
a chance to mismatch.  This module emits all four ``.fdf``s from one
descriptor (so the § 6.7 numerical contract is identical by construction)
plus a driver script that performs the hand-offs:

* **relax → device:** copy ``<job>_relax.XV`` → ``<job>.XV``; the device
  fdf carries ``MD.UseSaveXV .true.`` so SIESTA starts from the relaxed
  geometry instead of the unrelaxed coordinate block.
* **electrode → device:** the wizard already names each lead
  ``<job>_<label>.TSHS`` — exactly the device fdf's ``TS.Elec.<name> HS``
  reference — so no rename is needed (the win over the old flow).

Dependency insight: the **electrodes are independent of the relax**.  The
leads are the *frozen* bulk geometry (they don't move during device
relaxation, § 6.2), so the two electrode runs and the relax run have no
ordering constraint among themselves; only the device run depends on all
three.  The driver reflects this (electrodes + relax first, device last).

Scope: this emits a *bundle* (fdfs + a driver shell script) for the user
to run under ``molbuilder-siesta`` on their target.  It does NOT execute
SIESTA — same philosophy as the benchmark bundle.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

from ..config.transport import TransportConfig
from ..structure import Structure
from .transiesta import (
    TransiestaEngine,
    _emit_basis_and_xc,
    _emit_geometry,
    _emit_k_mesh,
    _find_electrode_regions,
)
from .wizard import DEFAULT_ELECTRODE_KZ, electrode_wizard

# Default CG steps for the device-geometry relaxation.  A real junction
# needs the scattering region + first lead layers to settle; 0 would
# skip relaxation entirely (single point).  This is a starting point —
# the user converges it (forces) like any geometry optimization.
DEFAULT_RELAX_STEPS = 100


@dataclass
class TransportBundle:
    """Everything needed to run the 3-run workflow on a target.

    ``files`` maps relative filename → text content (the caller writes
    them).  ``driver`` is the filename of the run script within
    ``files``.  ``electrode_labels`` records which leads were derived.
    """

    files: Dict[str, str]
    driver: str
    job_name: str
    electrode_labels: List[str]
    relaxed_frozen: List[int]
    notes: List[str] = field(default_factory=list)


def _frozen_for_relax(device: Structure) -> List[int]:
    """0-based indices to freeze during the device relaxation.

    Prefer the structure's explicit ``frozen_atoms``; otherwise freeze
    every atom in a ``*-electrode`` region (the leads stay at their bulk
    geometry while the scattering region relaxes, § 6.2).
    """
    if device.frozen_atoms:
        return sorted(set(device.frozen_atoms))
    frozen: set = set()
    for _label, _name, idxs in _find_electrode_regions(device):
        frozen.update(idxs)
    return sorted(frozen)


def render_relax_fdf(device: Structure, cfg: TransportConfig,
                     *, relax_steps: int = DEFAULT_RELAX_STEPS) -> str:
    """Emit the device-geometry relaxation ``.fdf`` (regular SIESTA).

    Same numerical contract (basis/XC/MeshCutoff/EnergyShift) + same
    transverse k as the device — so the relaxed geometry is produced on
    the *same footing* it will be transported on.  The ``*-electrode``
    atoms are frozen via ``%block Geometry.Constraints`` (verified syntax,
    ``siesta/input.py``).  No ``TS.*`` blocks — this is a plain SCF/CG run.
    """
    job = f"{cfg.job_name}_relax"
    frozen = _frozen_for_relax(device)
    L: List[str] = [
        "# ================================================================== #",
        f"#  Device-geometry RELAXATION .fdf — {job}",
        "#  Generated by molbuilder transport orchestration (§ 6.4).",
        "#  Step 1 of 3: relax the scattering region with the leads frozen.",
        "#  Output <job>.XV is handed to the device run (MD.UseSaveXV).",
        "# ================================================================== #",
        "",
        f"SystemLabel            {job}",
        f"SystemName             Device relaxation for {cfg.job_name}",
        "",
    ]
    L += _emit_geometry(device)
    L += _emit_basis_and_xc(cfg)
    L += _emit_k_mesh(cfg)
    # Frozen-lead constraints (1-based; verified against SIESTA 5.4.2).
    if frozen:
        L += [
            "# --- Frozen leads (the electrodes stay at bulk geometry) ---",
            "# 1-based indices SIESTA's relaxer must NOT move (§ 6.2).",
            "%block Geometry.Constraints",
        ]
        ids = [i + 1 for i in frozen]
        for i in range(0, len(ids), 20):
            L.append("position " + " ".join(str(x) for x in ids[i:i + 20]))
        L += ["%endblock Geometry.Constraints", ""]
    L += [
        "# --- Geometry relaxation ---",
        "MD.TypeOfRun           CG",
        f"MD.NumCGsteps          {int(relax_steps)}",
        "MD.MaxForceTol         0.02 eV/Ang",
        "",
    ]
    return "\n".join(L) + "\n"


def _device_fdf_with_relaxed_geometry(device: Structure,
                                      cfg: TransportConfig) -> str:
    """The TranSIESTA device fdf + the relax hand-off flag.

    Reuses the validated emitter and injects ``MD.UseSaveXV .true.`` so
    the device run starts from ``<job>.XV`` (copied from the relax run by
    the driver) instead of the unrelaxed coordinate block.
    """
    fdf = TransiestaEngine.render_script(device, cfg)
    inject = (
        "# --- Relaxed-geometry hand-off (orchestration § 6.4) ---\n"
        "# The driver copies <job>_relax.XV -> <job>.XV; this flag makes\n"
        "# SIESTA read the relaxed coordinates from it (the coordinate\n"
        "# block above is the unrelaxed fallback if the .XV is absent).\n"
        "MD.UseSaveXV           .true.\n\n"
    )
    # Place the flag right after the geometry block so it reads naturally.
    marker = "%endblock AtomicCoordinatesAndAtomicSpecies\n"
    idx = fdf.find(marker)
    if idx == -1:
        return inject + fdf
    cut = idx + len(marker)
    # skip a single trailing blank line if present
    rest = fdf[cut:]
    if rest.startswith("\n"):
        cut += 1
    return fdf[:cut] + "\n" + inject + fdf[cut:]


def render_driver(job_name: str, electrode_jobs: List[str]) -> str:
    """Emit ``run-transport.sh`` — the 3-run driver with hand-offs.

    Binaries + launcher are parameterized (``SIESTA``, ``TBTRANS``,
    ``MPI``) so the same script runs on a workstation or a scheduler
    node; the four-env model means the user runs it under
    ``molbuilder-siesta``.  Each step checks its expected output exists
    before the next consumes it.
    """
    relax_job = f"{job_name}_relax"
    elec_lines: List[str] = []
    for ej in electrode_jobs:
        elec_lines.append(f'  run_siesta "{ej}"          "{ej}.TSHS"')
    elec_block = "\n".join(elec_lines)

    return f"""#!/usr/bin/env bash
# ===================================================================== #
#  run-transport.sh — 3-run TranSIESTA driver (molbuilder § 6.4)
#
#  relax ─┐
#         ├─▶ device (NEGF) ─▶ tbtrans ─▶ T(E), G0
#  leads ─┘
#
#  Run under the `molbuilder-siesta` conda env (four-env model):
#      conda activate molbuilder-siesta
#      bash run-transport.sh
#
#  Override the binaries / launcher if needed:
#      SIESTA=siesta TBTRANS=tbtrans MPI="mpirun -np 8" bash run-transport.sh
# ===================================================================== #
set -euo pipefail

SIESTA="${{SIESTA:-siesta}}"
TBTRANS="${{TBTRANS:-tbtrans}}"
MPI="${{MPI:-mpirun -np 4}}"

run_siesta() {{   # <label> <expected-output>
  local label="$1" expect="$2"
  echo "[transport] === $label ==="
  $MPI "$SIESTA" "$label.fdf" > "$label.out" 2>&1
  if [ ! -e "$expect" ]; then
    echo "[transport] FAILED: $label did not produce $expect" >&2
    echo "[transport] see $label.out for the SIESTA error" >&2
    exit 1
  fi
  echo "[transport] $label -> $expect  OK"
}}

# --- Steps 1a/1b: bulk electrodes (independent; write their .TSHS) ---
{elec_block}

# --- Step 1c: relax the device geometry (leads frozen) ---
  run_siesta "{relax_job}"   "{relax_job}.XV"

# --- Hand-off: relaxed coordinates -> device run ---
echo "[transport] hand-off: {relax_job}.XV -> {job_name}.XV"
cp "{relax_job}.XV" "{job_name}.XV"

# --- Step 2: device NEGF (needs the electrode .TSHS + the device .XV) ---
  run_siesta "{job_name}"    "{job_name}.TSHS"

# --- Step 3: transmission ---
echo "[transport] === tbtrans: {job_name} ==="
$MPI "$TBTRANS" "{job_name}.fdf" > "{job_name}.tbtrans.out" 2>&1
echo "[transport] tbtrans done; see {job_name}.TBT.* for T(E)."
echo "[transport] ALL DONE."
"""


def render_manifest(bundle_job: str, electrode_labels: List[str],
                    frozen: List[int]) -> str:
    """A README documenting the bundle + the run order + hand-offs."""
    leads = ", ".join(electrode_labels)
    return f"""TranSIESTA transport bundle — {bundle_job}
=================================================

Generated by `molbuilder transport bundle` (orchestration § 6.4).
All four .fdf files share ONE numerical contract by construction
(XC / MeshCutoff / EnergyShift / basis / transverse k); run
`molbuilder transport preflight` to confirm the device<->electrode pair.

Files
-----
  {bundle_job}_relax.fdf      device geometry relaxation (leads frozen)
  {bundle_job}_<lead>.fdf     bulk electrode runs  ({leads})
  {bundle_job}.fdf            device NEGF (TranSIESTA) + tbtrans blocks
  run-transport.sh            the driver (run this)

Run order (the driver does this for you)
----------------------------------------
  1. electrodes + relax   (independent of each other)
  2. hand-off             cp {bundle_job}_relax.XV -> {bundle_job}.XV
  3. device NEGF          reads the relaxed .XV + the electrode .TSHS
  4. tbtrans              transmission T(E), G0

Frozen during relax: {len(frozen)} lead atoms (0-based) {frozen if len(frozen) <= 20 else str(frozen[:20]) + ' ...'}

Run it (four-env model):
    conda activate molbuilder-siesta
    bash run-transport.sh
"""


def build_transport_bundle(
    device: Structure,
    cfg: TransportConfig,
    *,
    electrode_kz: int = DEFAULT_ELECTRODE_KZ,
    relax_steps: int = DEFAULT_RELAX_STEPS,
    z_period: Optional[float] = None,
) -> TransportBundle:
    """Derive the full relax/electrode/device bundle from one device.

    Returns a :class:`TransportBundle` whose ``files`` the caller writes
    to disk.  The electrode fdfs come from the wizard (geometry clone +
    contract), the device fdf from the validated emitter (+ the relax
    hand-off flag), and the relax fdf from :func:`render_relax_fdf`.
    """
    electrodes = electrode_wizard(
        device, cfg, which="both", electrode_kz=electrode_kz,
        z_period=z_period)
    electrode_jobs = [job for job, _fdf, _m in electrodes]
    electrode_labels = [m.label for _job, _fdf, m in electrodes]
    frozen = _frozen_for_relax(device)

    files: Dict[str, str] = {}
    for job, fdf, _m in electrodes:
        files[f"{job}.fdf"] = fdf
    files[f"{cfg.job_name}_relax.fdf"] = render_relax_fdf(
        device, cfg, relax_steps=relax_steps)
    files[f"{cfg.job_name}.fdf"] = _device_fdf_with_relaxed_geometry(
        device, cfg)
    files["run-transport.sh"] = render_driver(cfg.job_name, electrode_jobs)
    files["README.txt"] = render_manifest(
        cfg.job_name, electrode_labels, frozen)

    notes: List[str] = []
    for _job, _fdf, m in electrodes:
        notes.extend(f"[{m.label}] {n}" for n in m.notes)
    if not frozen:
        notes.append(
            "no atoms frozen for relax: the structure has no frozen_atoms "
            "and no *-electrode regions to freeze — the WHOLE device will "
            "relax (the leads will drift off their bulk geometry).")

    return TransportBundle(
        files=files, driver="run-transport.sh", job_name=cfg.job_name,
        electrode_labels=electrode_labels, relaxed_frozen=frozen,
        notes=notes)


def format_bundle(bundle: TransportBundle) -> str:
    """Human-readable summary of a derived bundle."""
    lines = [f"transport bundle — {bundle.job_name}", ""]
    for name in sorted(bundle.files):
        lines.append(f"  {name}")
    lines.append("")
    lines.append(f"  leads: {', '.join(bundle.electrode_labels)}")
    lines.append(f"  frozen during relax: {len(bundle.relaxed_frozen)} atoms")
    for n in bundle.notes:
        lines.append(f"  - {n}")
    return "\n".join(lines)


__all__ = [
    "TransportBundle",
    "render_relax_fdf",
    "render_driver",
    "render_manifest",
    "build_transport_bundle",
    "format_bundle",
    "DEFAULT_RELAX_STEPS",
]
