"""``bench prep-run`` -- turn the benchmark verdict into a production run.

The last target-side step (benchmark-workflow.md § 7.5): read the portable
``choice`` from ``bench-result.json``, **re-detect the LOCAL environment**,
and hand both to the adapter's ``format_run`` -- which re-resolves the
machine-specific knobs here (§ 5.4: the mechanism transfers, the concrete
``-n``/``-c``/``-G`` are recomputed for THIS machine).  Writes
``run-production.sh``.

Re-detection (not the bench-result's embedded environment) is deliberate:
prep-run may run on a different machine than the benchmark did, and the
whole point of § 5.4 is that the choice ports while the concrete launch
adapts.  The embedded environment stays in the bench-result for provenance.

PREREQUISITE: the production scripts (``<script_base>.fdf`` + ``.run.sh``
[+ ``.sbatch``]) must already exist and be engine-correct for
``choice.engine`` (generated by ``bench generate`` / ``molbuilder run``).
prep-run produces the *invocation*, not the engine input.

**Stdlib-only**; ``run_prep_run`` is the testable core, ``main`` the
standalone entry, ``molbuilder bench prep-run`` calls the core.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, Optional, Tuple

from .adapters import get_adapter
from .environment import Environment, resolve_environment
from .result import BenchResult


def run_prep_run(bench_result_path,
                 *,
                 script_base: str = "job",
                 out=None,
                 scheduler_override: Optional[str] = None,
                 overrides: Optional[dict] = None,
                 now_iso: Optional[str] = None
                 ) -> Tuple[Environment, Dict, Path]:
    """Read ``bench-result.json``, re-resolve the local Environment, and
    write ``run-production.sh`` for the winning mechanism applied to
    ``script_base``.  Returns ``(Environment, choice, out_path)``.
    """
    brp = Path(bench_result_path)
    try:
        res = BenchResult.from_dict(json.loads(
            brp.read_text(encoding="utf-8")))
    except (OSError, ValueError) as exc:
        raise ValueError(f"could not read bench-result {brp}: {exc}") from exc

    if not res.choice:
        raise ValueError(
            f"{brp.name} has no 'choice' (no completed point won the "
            f"benchmark); nothing to prep a run from.")

    env = resolve_environment(overrides=overrides or None,
                              scheduler_override=scheduler_override,
                              now_iso=now_iso)
    adapter = get_adapter(env)
    files = adapter.format_run(res.choice, env, script_base=script_base)

    out_path = (Path(out) if out is not None
                else brp.parent / "run-production.sh")
    out_path.write_text(files["run-production.sh"], encoding="utf-8")
    out_path.chmod(0o755)
    return env, res.choice, out_path


def _summary(env: Environment, choice: Dict, out_path: Path) -> str:
    return "\n".join([
        "prep-run: production run formatted for this machine",
        f"  scheduler : {env.scheduler}",
        f"  winner    : engine={choice.get('engine')} "
        f"knobs={choice.get('knobs')}",
        f"  rationale : {choice.get('rationale')}",
        f"  wrote     : {out_path}",
        "  (submit/launch it; ensure the production scripts exist + are "
        "engine-correct)",
    ])


def main(argv=None) -> int:
    import argparse
    p = argparse.ArgumentParser(
        prog="prep-run",
        description="Format the production run from a benchmark verdict "
                    "(bench-result.json), re-resolved for THIS machine.")
    p.add_argument("--bench-result", default="bench-result.json",
                   help="path to bench-result.json (default: ./)")
    p.add_argument("--script-base", default="job",
                   help="basename of the production scripts "
                        "(<base>.fdf/.run.sh/.sbatch).")
    p.add_argument("--out", default=None,
                   help="output path (default: run-production.sh beside the "
                        "bench-result).")
    p.add_argument("--scheduler", choices=["slurm", "workstation"],
                   default=None, help="force the scheduler (else detected).")
    p.add_argument("--cores-per-socket", type=int, default=None)
    p.add_argument("--gpus-per-node", type=int, default=None)
    p.add_argument("--gpu-type", default=None)
    a = p.parse_args(argv)

    from .prep import _overrides_from, utc_now_iso
    env, choice, out_path = run_prep_run(
        a.bench_result,
        script_base=a.script_base,
        out=a.out,
        scheduler_override=a.scheduler,
        overrides=_overrides_from(a.cores_per_socket, a.gpus_per_node,
                                  a.gpu_type),
        now_iso=utc_now_iso())
    print(_summary(env, choice, out_path))
    return 0


__all__ = ["run_prep_run", "main"]


if __name__ == "__main__":
    raise SystemExit(main())
