#!/usr/bin/env bash
#
# bench-siesta-blocksize.sh -- sweep SIESTA BlockSize values on a real
# project's .fdf and report wall-time per SCF iter for each value.
#
# Motivation: 2026-06-16 -- the molbuilder generator's auto-picker
# defaults to BlockSize=256 for typical GPU runs based on first-
# principles reasoning (kernel launch overhead amortization,
# n_orbitals/mpi_np load balance, ELPA CUDA kernel range).  The
# "right" number for a given problem + hardware combo is
# fundamentally measured, not derived.  This script does the
# measurement.
#
# What it does:
#
#   1. Copies the project's <basename>.fdf to bench-bs<N>/<basename>.fdf
#      for each BlockSize in the sweep list (default: 32 64 128 256).
#   2. Edits each copy: BlockSize <N>; MaxSCFIterations <K> (default 5);
#      removes MD.NumCGsteps so it stops after a single SCF, no relax.
#   3. Runs each variant in turn with the same wrapper / ranks / GPU.
#   4. Greps the .out for the SCF wall times, computes mean of iters 2-N
#      (skips iter 1 which carries bootstrap cost), prints a comparison
#      table sorted by wall.
#
# Total runtime: K iters x len(bs_list) x (~10-30 s per iter on this
# hardware for 212-atom systems).  With defaults (K=5, 4 BSs):
# 4 x 5 x 20 s ≈ 7 minutes.
#
# Usage:
#   bash scripts/bench-siesta-blocksize.sh <project-dir> [bs1 bs2 ...]
#
# Example:
#   bash scripts/bench-siesta-blocksize.sh \\
#     ~/molbuilder/projects/BDT/optimization/BDT-withAuJunction-siesta-gpu \\
#     32 64 128 256
#
# Constraints:
#   * The project must already have a .fdf + working .run.sh in it
#     (generated by molbuilder).  This script does NOT re-generate.
#   * Existing .DM / .CG warm-start files in the project ARE used
#     (faster bench).  Pass --cold to wipe them between runs.
#   * Bench .out files written into bench-bs<N>/ subdirs to avoid
#     trampling the main project run.
#
set -euo pipefail


# ---------- args ----------

# Handle --help / -h before any path validation.
case "${1:-}" in
    --help|-h)
        sed -n '4,40p' "$0"
        exit 0 ;;
    "")
        echo "usage: $0 <project-dir> [bs1 bs2 ...] [--iters N] [--cold]" >&2
        echo "       defaults: --iters 5  BlockSize sweep: 32 64 128 256" >&2
        echo "       $0 --help  for full docs" >&2
        exit 2 ;;
esac

PROJ="$1"
shift

# Parse remaining args: BlockSizes + optional --iters / --cold.
ITERS=5
COLD=0
BSS=()
while [ $# -gt 0 ]; do
    case "$1" in
        --iters)   ITERS="$2"; shift 2 ;;
        --cold)    COLD=1; shift ;;
        --help|-h) sed -n '4,40p' "$0"; exit 0 ;;
        [0-9]*)    BSS+=("$1"); shift ;;
        *) echo "ERROR: unknown arg: $1" >&2; exit 2 ;;
    esac
done
[ ${#BSS[@]} -eq 0 ] && BSS=(32 64 128 256)

if [ ! -d "$PROJ" ]; then
    echo "ERROR: project dir does not exist: $PROJ" >&2
    exit 2
fi
PROJ="$(cd "$PROJ" && pwd)"


# ---------- find the .fdf + .run.sh in the project ----------

FDF=""
for f in "$PROJ"/*.fdf; do
    case "$f" in
        */bench-bs*) continue ;;
    esac
    if [ -f "$f" ]; then FDF="$f"; break; fi
done
if [ -z "$FDF" ]; then
    echo "ERROR: no .fdf found in $PROJ" >&2
    exit 2
fi
BASENAME="$(basename "$FDF" .fdf)"
RUNSH="$PROJ/${BASENAME}.run.sh"
if [ ! -f "$RUNSH" ]; then
    echo "ERROR: expected wrapper $RUNSH not found" >&2
    echo "       (run molbuilder's Generate Script first)" >&2
    exit 2
fi

echo "==== bench-siesta-blocksize ===="
echo "project : $PROJ"
echo "fdf     : $FDF"
echo "wrapper : $RUNSH"
echo "iters   : $ITERS per BlockSize (SCF only, no MD)"
echo "cold    : $COLD"
echo "sweep   : ${BSS[*]}"
echo


# ---------- per-BlockSize run ----------

# Edit one .fdf in place: set BlockSize, cap MaxSCFIterations,
# disable MD (we want just SCF timing).
edit_fdf() {
    local src="$1" dst="$2" bs="$3" iters="$4"
    # sed -E to avoid escaping pain; uppercase keywords match SIESTA's
    # case-insensitive parse.  Lines starting with comment "#" are
    # left alone -- we only edit the live setting.
    awk -v bs="$bs" -v it="$iters" '
        BEGIN { saw_bs=0; saw_it=0; saw_md=0 }
        /^[[:space:]]*BlockSize[[:space:]]/    { print "BlockSize          " bs " # bench-override"; saw_bs=1; next }
        /^[[:space:]]*MaxSCFIterations[[:space:]]/ { print "MaxSCFIterations  " it " # bench-override"; saw_it=1; next }
        /^[[:space:]]*MD\.NumCGsteps[[:space:]]/   { print "MD.NumCGsteps  0 # bench-override (SCF-only)"; saw_md=1; next }
        { print }
        END {
            if (!saw_bs) print "BlockSize          " bs " # bench-override (added)"
            if (!saw_it) print "MaxSCFIterations  " it " # bench-override (added)"
            if (!saw_md) print "MD.NumCGsteps  0 # bench-override (added)"
        }
    ' "$src" > "$dst"
}

results_csv="$PROJ/bench-results-$(date +%Y%m%d-%H%M%S).csv"
echo "blocksize,scf_iters_done,avg_s_per_iter,first_iter_s,effective_bs" > "$results_csv"

for bs in "${BSS[@]}"; do
    benchdir="$PROJ/bench-bs${bs}"
    mkdir -p "$benchdir"
    bench_fdf="$benchdir/${BASENAME}.fdf"
    edit_fdf "$FDF" "$bench_fdf" "$bs" "$ITERS"

    # Symlink siblings (.psml, .ion, .ion.nc, .DM/.CG/.XV warm-start)
    # so SIESTA finds them.  --cold removes the warm-start.
    for sib in "$PROJ"/*.psml "$PROJ"/*.ion "$PROJ"/*.ion.nc "$PROJ"/*.ion.xml; do
        [ -e "$sib" ] && ln -sfn "$sib" "$benchdir/$(basename "$sib")"
    done
    if [ "$COLD" = 0 ]; then
        for sib in "$PROJ"/${BASENAME}.DM "$PROJ"/${BASENAME}.CG "$PROJ"/${BASENAME}.XV "$PROJ"/siesta.DM "$PROJ"/siesta.CG "$PROJ"/siesta.XV; do
            [ -e "$sib" ] && cp "$sib" "$benchdir/" || true
        done
    fi

    # Copy the wrapper and adjust paths so it runs out of benchdir.
    bench_runsh="$benchdir/${BASENAME}.run.sh"
    cp "$RUNSH" "$bench_runsh"
    chmod +x "$bench_runsh"

    out="$benchdir/${BASENAME}-run0.out"
    rm -f "$benchdir/${BASENAME}-run0.out" "$benchdir/${BASENAME}-run0.bench.out"

    echo "==== BlockSize=$bs : running ===="
    start_epoch=$(date +%s)
    (cd "$benchdir" && bash "${BASENAME}.run.sh" --force) > /dev/null 2>&1 || true
    end_epoch=$(date +%s)
    walltime=$((end_epoch - start_epoch))

    n_done=$(grep -cE '^   scf:' "$out" 2>/dev/null || echo 0)
    # SIESTA's timer line format:
    #   timer: Routine,Calls,Time,% = IterSCF   1   54.187   39.48
    # field $4=IterSCF, $5=calls, $6=time(s), $7=%.  An earlier
    # version grabbed $5 (calls) and reported "1" as if it were
    # seconds, which made the avg-iter formula wrong.
    first=$(grep -E 'timer:.*IterSCF' "$out" 2>/dev/null | head -1 | awk '{print $6}')
    [ -z "$first" ] && first="?"
    # Sanity check: did the BlockSize edit actually take effect?
    # SIESTA echoes the effective BlockSize in the .out as
    # "redata: BlockSize" or in diag: lines.
    effective_bs=$(grep -iE 'BlockSize' "$out" 2>/dev/null \
                   | grep -vE 'auto|comment' \
                   | head -1 | awk '{for(i=1;i<=NF;i++) if($i ~ /^[0-9]+$/) {print $i; break}}')
    [ -z "$effective_bs" ] && effective_bs="?"
    if [ "$n_done" -gt 1 ]; then
        # Trust wall - first-iter cost as the "steady-state" cost
        # over n_done - 1 iters.  Rough; SIESTA's own timer is more
        # accurate but only writes at end-of-run.
        if [ "$first" != "?" ]; then
            iter_cost=$(awk -v w=$walltime -v f="$first" -v n="$n_done" \
                'BEGIN { printf "%.1f", (w - f) / (n - 1) }')
        else
            iter_cost=$(awk -v w=$walltime -v n="$n_done" \
                'BEGIN { printf "%.1f", w / n }')
        fi
    else
        iter_cost="?"
    fi
    # Surface the effective BlockSize so the user can confirm the
    # edit actually applied (silent BlockSize mismatch was a real
    # script bug on 2026-06-16).
    bs_check=""
    if [ "$effective_bs" != "?" ] && [ "$effective_bs" != "$bs" ]; then
        bs_check=" [WARN effective=$effective_bs]"
    fi
    echo "BlockSize=$bs : iters=$n_done first=${first}s avg/iter=${iter_cost}s wall=${walltime}s${bs_check}"
    echo "$bs,$n_done,$iter_cost,$first,$effective_bs" >> "$results_csv"
done


echo
echo "==== results sorted by avg s/iter (winner first) ===="
{
    head -1 "$results_csv"
    tail -n +2 "$results_csv" | sort -t, -k3 -n
} | column -t -s,
echo
echo "csv: $results_csv"
echo
echo "Notes:"
echo " * first iter excluded from avg (bootstrap cost is ~2-5x normal)"
echo " * --cold not used means .DM warm-start was carried -- compares"
echo "   from a converged starting density, isolating diag-step cost"
echo " * for a fair compare across runs, kill other GPU jobs first"
