#!/usr/bin/env python3
"""Capture the 10 PNG screenshots referenced by the top-level README.

Usage:
    conda run -n molbuilder-tests \\
        python scripts/capture-readme-screenshots.py

Spawns a temporary ``molbuilder serve`` process (no auth, no TLS) on a
free port, drives Chromium via Playwright through each of the 10
shots documented in ``docs/img/SCREENSHOTS.md``, and writes the PNGs
to ``docs/img/``.  Re-runnable: idempotent overwrite of every PNG.

Demo data: ``projects/BDT/`` (the Au-BDT-Au junction).  Each shot uses
the BDT example so the README reads as one continuous example.

Cleanup:
* The temp config is deleted on exit (success OR failure).
* The molbuilder server is terminated on exit.
* If Playwright fails mid-flight, the partial screenshot set is left
  in place so you can see which shot crashed.

Design notes:
* Runs Chromium with a fixed 1440x900 viewport so screenshots are a
  family, not random sizes.
* Light theme (browser default) per SCREENSHOTS.md.
* Page-level captures use full_page=False with a fixed clip box per
  shot; element-level captures use locator.screenshot() so the bounding
  box is exact.
* Wait strategy: ``page.wait_for_load_state("networkidle")`` plus an
  extra ~600 ms idle so 3Dmol's WebGL has time to render the molecule.
"""

from __future__ import annotations

import json
import os
import shutil
import socket
import subprocess
import sys
import tempfile
import time
from contextlib import contextmanager
from pathlib import Path
from typing import Iterator

REPO_ROOT = Path(__file__).resolve().parent.parent
IMG_DIR = REPO_ROOT / "docs" / "img"
DEMO_PROJECT = "BDT"
DEMO_STRUCTURE = "BDT-AuJunction_siestaStage1_optimized.xyz"

VIEWPORT_W = 1440
VIEWPORT_H = 900

# Idle delay (seconds) after navigation to let WebGL render.  Tunable
# per shot; 3Dmol's mol load + camera fit takes ~400-700 ms depending
# on system count.
IDLE_AFTER_NAV_S = 1.2


def _free_port() -> int:
    """Return a TCP port not currently in use on localhost."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def _write_temp_config(tmp_dir: Path) -> Path:
    """Write a minimal molbuilder.json: no auth, no TLS.

    Returns the path; caller owns deletion.
    """
    cfg = {
        "_comment":
            "Temporary capture config -- generated by "
            "scripts/capture-readme-screenshots.py.  No auth, no TLS.",
    }
    p = tmp_dir / "molbuilder-capture.json"
    p.write_text(json.dumps(cfg, indent=2))
    return p


@contextmanager
def _serve(port: int, config_path: Path) -> Iterator[subprocess.Popen]:
    """Spawn ``molbuilder serve`` on ``port`` with the capture config.

    The server runs in the ``MOLBUILDER_HOST_ENV`` env (default
    ``molbuilder``) which has numpy / sisl / flask / etc.  This
    capture script itself runs in ``molbuilder-tests`` (has
    Playwright) -- two different envs for two different concerns.
    Dispatch via ``conda run`` (or whichever env manager molbuilder
    autodetected) so the right Python interpreter is used.

    Yields the Popen handle; terminates the child on exit (SIGTERM,
    then SIGKILL after 5 s grace).
    """
    env = dict(os.environ)
    env["MOLBUILDER_CONFIG"] = str(config_path)
    # Pick the env manager the same way diagnostics._find_conda_binary
    # does -- mamba > micromamba > conda -- so we work on HPC where
    # only mamba may be installed.
    env_mgr = (shutil.which("mamba") or shutil.which("micromamba")
               or shutil.which("conda"))
    if env_mgr is None:
        raise RuntimeError(
            "no conda/mamba/micromamba on PATH; cannot dispatch "
            "molbuilder serve.  Activate the molbuilder host env "
            "manually and re-run.")
    host_env = os.environ.get("MOLBUILDER_HOST_ENV", "molbuilder")
    cmd = [
        env_mgr, "run", "-n", host_env, "--no-capture-output",
        "python", "-m", "molbuilder", "serve",
        "--port", str(port),
        "--host", "127.0.0.1",
    ]
    # Capture server output to a log file so the PIPE buffer can't
    # block the server mid-startup; the log is dropped on success +
    # surfaced on failure for diagnostics.
    server_log = tempfile.NamedTemporaryFile(
        prefix="molbuilder-serve-", suffix=".log",
        delete=False, mode="w",
    )
    proc = subprocess.Popen(
        cmd, env=env, cwd=str(REPO_ROOT),
        stdout=server_log, stderr=subprocess.STDOUT,
        text=True,
    )
    proc._server_log_path = server_log.name  # type: ignore[attr-defined]
    server_log.close()
    # Probe-wait for the server to bind.  ~10 s budget; abort the
    # capture if it doesn't come up (no point hammering Playwright at
    # a dead URL).
    deadline = time.time() + 20.0
    last_err = None
    while time.time() < deadline:
        try:
            with socket.create_connection(("127.0.0.1", port), timeout=0.5):
                break
        except OSError as e:
            last_err = e
            time.sleep(0.2)
    else:
        # Drain server output from the log file for diagnostics.
        try:
            out = Path(proc._server_log_path).read_text()  # type: ignore[attr-defined]
        except OSError:
            out = "(server log unreadable)"
        proc.terminate()
        raise RuntimeError(
            f"molbuilder serve did not bind to 127.0.0.1:{port} within "
            f"20 s (last connect err: {last_err}).  Server output:\n{out}"
        )

    try:
        yield proc
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=5.0)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait()
        # Clean up the server log file.
        try:
            os.unlink(getattr(proc, "_server_log_path", "/nonexistent"))
        except OSError:
            pass


def _capture_each(page, base_url: str) -> None:
    """Capture each of the 10 README screenshots in order.

    ``page`` is a Playwright Page already configured with the fixed
    viewport.  ``base_url`` is the running ``molbuilder serve`` root
    (e.g. ``http://127.0.0.1:54321``).
    """
    def goto(path: str) -> None:
        page.goto(f"{base_url}{path}",
                  wait_until="networkidle", timeout=30_000)
        time.sleep(IDLE_AFTER_NAV_S)

    def shot(filename: str, locator=None) -> None:
        out = IMG_DIR / filename
        if locator is not None:
            locator.screenshot(path=str(out), type="png")
        else:
            page.screenshot(path=str(out), type="png",
                            full_page=False)
        size_kb = out.stat().st_size / 1024
        print(f"  wrote {out.relative_to(REPO_ROOT)} "
              f"({size_kb:.0f} KB)")

    print("[1/10] hero-molbuilder.png  -- /molbuilder, full content area")
    goto(f"/molbuilder?project={DEMO_PROJECT}&file={DEMO_STRUCTURE}")
    shot("hero-molbuilder.png")

    print("[2/10] tab-bar.png  -- top tab strip")
    goto("/molbuilder")
    # Locate the tab strip.  The route nav lives in ``.app-tab-bar``
    # (or similar) -- use any element near the top spanning the
    # navigation; fall back to a full-width slice if the locator
    # misses.
    nav = page.locator("nav, .tab-bar, .app-tabs, header").first
    if nav.count():
        shot("tab-bar.png", locator=nav)
    else:
        # Top 60 px slice fallback.
        page.screenshot(path=str(IMG_DIR / "tab-bar.png"),
                        clip={"x": 0, "y": 0,
                              "width": VIEWPORT_W, "height": 80})
        print(f"  (fallback clip; tab-bar nav locator missed)")

    print("[3/10] sidebar-projects.png  -- projects sidebar column")
    goto(f"/molbuilder?project={DEMO_PROJECT}")
    sidebar = page.locator(".projects-sidebar, #projects-sidebar, "
                           "aside.sidebar, [data-projects-sidebar]").first
    if sidebar.count():
        shot("sidebar-projects.png", locator=sidebar)
    else:
        page.screenshot(path=str(IMG_DIR / "sidebar-projects.png"),
                        clip={"x": 0, "y": 0,
                              "width": 360, "height": VIEWPORT_H})

    print("[4/10] molbuilder-workspace.png  -- workspace 3-panel layout")
    goto(f"/molbuilder?project={DEMO_PROJECT}&file={DEMO_STRUCTURE}")
    workspace = page.locator(".workspace, .main-content, "
                             "main, [data-workspace]").first
    if workspace.count():
        shot("molbuilder-workspace.png", locator=workspace)
    else:
        shot("molbuilder-workspace.png")

    print("[5/10] structure-optimization-form.png")
    goto(f"/structure-optimization?project={DEMO_PROJECT}&"
         f"file={DEMO_STRUCTURE}")
    shot("structure-optimization-form.png")

    print("[6/10] spectrum-form.png")
    goto("/spectrum-calculation")
    form = page.locator("form, .form-panel, .build-form, "
                        "[data-build-form]").first
    if form.count():
        shot("spectrum-form.png", locator=form)
    else:
        shot("spectrum-form.png")

    print("[7/10] transport-form.png")
    goto(f"/transport-calculation?project={DEMO_PROJECT}&"
         f"file={DEMO_STRUCTURE}")
    shot("transport-form.png")

    print("[8/10] results-trajectory.png")
    goto(f"/results?project={DEMO_PROJECT}&"
         f"path=optimization/BDT-withAuJunction")
    shot("results-trajectory.png")

    print("[9/10] results-spectra.png")
    spectra_path = "spectrum/BDT-only"
    goto(f"/results?project={DEMO_PROJECT}&path={spectra_path}")
    shot("results-spectra.png")

    print("[10/10] results-bundle-card.png  -- bundle handoff card")
    goto(f"/results?project={DEMO_PROJECT}&"
         f"path=optimization/BDT-withAuJunction")
    bundle = page.locator(".bundle-card, [data-bundle-card], "
                          "section.bundle").first
    if bundle.count():
        shot("results-bundle-card.png", locator=bundle)
    else:
        # Crop the bottom-right area where the bundle card sits.
        page.screenshot(
            path=str(IMG_DIR / "results-bundle-card.png"),
            clip={"x": VIEWPORT_W - 820, "y": VIEWPORT_H - 380,
                  "width": 800, "height": 360},
        )


def main() -> int:
    # Sanity check: are we at the repo root?
    if not (REPO_ROOT / "molbuilder").is_dir():
        print(f"ERROR: expected {REPO_ROOT}/molbuilder/ to exist; "
              f"are we at the repo root?", file=sys.stderr)
        return 2
    if not (REPO_ROOT / "projects" / DEMO_PROJECT / "structure"
            / DEMO_STRUCTURE).is_file():
        print(f"ERROR: demo structure missing: "
              f"projects/{DEMO_PROJECT}/structure/{DEMO_STRUCTURE}",
              file=sys.stderr)
        return 2

    IMG_DIR.mkdir(parents=True, exist_ok=True)

    # Late import: Playwright is in molbuilder-tests env.  Fail
    # loudly if we were invoked outside that env.
    try:
        from playwright.sync_api import sync_playwright
    except ImportError as e:
        print(f"ERROR: playwright not importable ({e}).  Re-run as:",
              file=sys.stderr)
        print(f"  conda run -n molbuilder-tests "
              f"python {Path(__file__).relative_to(REPO_ROOT)}",
              file=sys.stderr)
        return 2

    port = _free_port()
    base_url = f"http://127.0.0.1:{port}"
    print(f"using port {port} -> {base_url}")

    with tempfile.TemporaryDirectory(prefix="molbuilder-capture-") as td:
        td_path = Path(td)
        cfg_path = _write_temp_config(td_path)
        print(f"wrote temp config: {cfg_path}")

        with _serve(port, cfg_path) as _proc:
            print(f"molbuilder serve up; opening Chromium...")
            with sync_playwright() as pw:
                browser = pw.chromium.launch(headless=True)
                ctx = browser.new_context(
                    viewport={"width": VIEWPORT_W, "height": VIEWPORT_H},
                    device_scale_factor=2,  # retina-style sharpness
                )
                page = ctx.new_page()
                try:
                    _capture_each(page, base_url)
                finally:
                    ctx.close()
                    browser.close()
        # _serve(...) closes its Popen here.

    print("")
    print(f"done.  {len(list(IMG_DIR.glob('*.png')))} PNG(s) under "
          f"{IMG_DIR.relative_to(REPO_ROOT)}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
