"""The receiving end for a run's own reports.

A job on a cluster tells you how it is going by POSTing here
(`execution/run-reports.md` § 4).  This module is the whole receiving end,
and it is deliberately the smallest thing that can be: it **appends one
line to a log and answers `{"ok": true}`**.

**Append-only is the security model, not a detail.**  `job-contracts.md`
gives the monitor its boundary -- *"it observes and notifies. It never
decides, and never mutates the calculation."*  The same holds one hop out.
A message that arrives becomes a line in a file: it is not parsed into
application state, does not touch a project, and cannot start, stop or
alter a job.  So the worst a stolen key buys is noise in a log one tab
reads.

**Four gates, and only one of them is the control.**

1. *Has anyone enabled this?*  The blueprint is registered only when
   **both** ``notify_keys_file`` and ``notify_route`` are configured
   (`app.py`).  Either missing and there is no route at any path.
2. *Where is it?*  A per-deployment random segment, generated by
   ``notify-token`` and never written in this repository -- a word chosen
   in the source would be exactly as public as ``notify``, only less
   honest about what it does (`access-control.md` § 8 rule 7).  The
   segment is **not** a secret: it appears in every access log, as any
   path does.  It is merely unguessable.
3. *May this sender write?*  **This is the control.**  An HMAC-SHA256
   signature over the exact body, compared with
   :func:`hmac.compare_digest`.
4. *What does a failure reveal?*  **Nothing** -- every one answers a plain
   404, so a wrong signature is indistinguishable from a path that was
   never registered.

**Why a signature and not a bearer token**, which is what this took until
2026-08-27.  A token proves *I know the secret* by sending it, so it is on
the wire on every report and one capture yields a credential good forever
and for any body.  A signature proves the same thing while the key stays
on the cluster, and what travels is valid for **one exact body**: it
cannot be altered, and it cannot mint a new report.  `access-control.md`
§ 8 rule 7 -- *prefer the secret that never travels.*

**Why every failure is 404 and not 401.**  A 401 answers the question the
other three gates exist to protect: it says *there is something here and
you got it wrong*.  Answering with the router's own 404 makes a wrong
signature look exactly like an unconfigured server -- rule 2, *absent
beats refused, when existence is itself the answer*.  It costs nothing:
404 is still 4xx, so `rate_limit.py` counts it exactly as it counted the
401 (``record_response`` takes any ``400 <= status < 500``).

**The limiter still hears about it.**  `auth.py`'s gate marks its own 401
as *not evidence* (``g.molbuilder_auth_challenge``) because an expired
session is an ordinary visitor -- counting it once locked a user out of
their own site for an hour.  **That reasoning does not carry here**:
nobody reaches this route by accident, so a failure is somebody trying.
This module never sets that flag.

**The gap, named rather than left to be found.**  HMAC is symmetric, so
reading the server's key file is enough to forge a report.  Ed25519 would
close it -- the cluster would hold a private key and this side only a
public one, making this file not a secret at all -- and it is not used
because it is **not in the standard library**, which `mb_monitor.py` is
restricted to: it ships to a compute node where molbuilder is not
installed and runs under whatever python the job's env has.
"""
from __future__ import annotations

import hashlib
import hmac
import json
import logging
import logging.handlers
import os
import re
import time
from collections import deque
from pathlib import Path
from typing import Any, Dict, NoReturn, Optional

from flask import Blueprint, abort, jsonify, request

bp = Blueprint("notify", __name__)

#: The body cap.  A run report is a handful of scalars; anything larger is
#: not one.  Enforced before parsing, so an oversized body is refused
#: without being read into memory as JSON first.
MAX_BODY_BYTES = 8 * 1024

#: The record's shape, stamped on every line.  A file that outlives the
#: session that made it needs to say which shape it is, or a reader a year
#: from now has to guess from the keys present.
SCHEMA = 1

#: What a report may carry.  A fixed set, because the record is rendered in
#: a browser and an open-ended blob is an open-ended rendering problem.
#:
#: **The first four are IDENTITY** and they are why this list grew on
#: 2026-08-27: a line used to read *"scf_converged, energy -1740.2"* with
#: nothing saying which calculation, on which machine, or when it was sent.
#: Two jobs running produced indistinguishable lines.  These are results,
#: not diagnostics -- somebody parses them later with no session to ask.
_FIELDS = ("run", "job", "array", "host", "sent_at",
           "event", "text", "state", "elapsed_s", "n_iters", "energy",
           "geom_step", "per_iter_s")

#: One rotating file per user, 1 MB × 5.  A cap is not optional on a file
#: fed from the internet: without one a leaked key fills the disk the
#: app itself runs on.  The limiter bounds the rate; this bounds the total.
LOG_BYTES = 1 * 1024 * 1024
LOG_KEEP = 5

#: A user id becomes a FILENAME, so it is constrained to what is safe as
#: one.  The ids come from the key file, which is the operator's own --
#: but a path separator in one would write outside the log directory, and
#: "the operator would not do that" is not a mechanism.
_SAFE_USER = re.compile(r"^[A-Za-z0-9._@+-]{1,128}$")

#: A VOLUME CAP, per key, on reports that pass every gate (user,
#: 2026-08-27: *we should have a rate-limit on the notify port too*).
#:
#: `rate_limit.py` bounds FAILURES -- its 404-storm signal counts 4xx -- and
#: its total-request threshold ships DISABLED (`threshold_total: 0`).  So a
#: valid key could POST without bound, and the harm is not the disk: the
#: record rotates at 1 MB x 5, so a flood would silently push a run's real
#: reports out of the window.  **A cap is what keeps the results the results.**
#:
#: Per KEY, not per IP: a cluster NATs every compute node behind one
#: address, so per-IP would punish somebody running several jobs for the
#: crime of using the machine they were given.
#:
#: Sixty a minute is generous by orders of magnitude.  A monitor speaks on
#: SCF convergence, every N hours, and once at the end -- a handful an hour
#: even when chatty (`run-reports.md` § 2, *looking often and speaking
#: rarely are different numbers*).
MAX_REPORTS_PER_MIN = 60
_RATE_WINDOW_S = 60.0

_loggers: Dict[str, logging.Logger] = {}
#: user -> arrival times inside the window.  Bounded by construction: the
#: deque is trimmed on every check and never grows past the cap.
_recent: Dict[str, "deque"] = {}


def _too_many(user: str, now: float) -> bool:
    """Has this key already sent its minute's worth?

    Trimmed in place, so the memory held is the cap and not the traffic --
    a flood must not become a way to spend the server's RAM instead of its
    disk.
    """
    q = _recent.setdefault(user, deque())
    cutoff = now - _RATE_WINDOW_S
    while q and q[0] < cutoff:
        q.popleft()
    if len(q) >= MAX_REPORTS_PER_MIN:
        return True
    q.append(now)
    return False


#: Results are written 0600 in a 0700 directory.  They were 0664 in an
#: 0775 directory, inheriting the umask -- so on a shared server anybody in
#: the group could read what your calculations were doing.  The KEY file
#: was always 0600; the DATA it protects was not, which is the wrong way
#: round.  (Found reviewing, 2026-08-27.)
REPORT_MODE = 0o600
REPORT_DIR_MODE = 0o700


def log_root() -> Path:
    """Where run reports are written.

    **`reports/`, not `logs/`, and the distinction is the point** (user,
    2026-08-27: *this is a different kind of log, not of the status of
    molbuilder but collection of computation results*).

    `~/.molbuilder/logs/` holds molbuilder's own operational output -- what
    the env installer did, what the server logged. Those are diagnostics:
    you read them when something is wrong, and you delete them when it is
    fixed. **These are measurements from calculations** -- energies,
    iteration counts, when a relaxation step landed. They are the kind of
    thing you keep, grep a year later, and plot. Filing them under `logs/`
    invited exactly one mistake: treating them as disposable.

    One file per user, JSON Lines, so `jq` and `pandas` both read it with
    no parser of ours in the middle.

    *(By the letter of the XDG spec this belongs under `$XDG_STATE_HOME`,
    as does `logs/`. Moving both is its own change.)* -- **done 2026-08-31**
    (`plans/config-access-plan.md` § 3.2): both now sit under the state
    directory, still in separate folders, so the distinction this docstring
    draws survives the move.
    """
    from ...runtime_config import reports_dir
    return reports_dir()


def read_keys(path: str) -> Dict[str, str]:
    """``{user: signing-key}`` from the operator's 0600 file, or ``{}``.

    Absent, unreadable or malformed all give ``{}`` — and ``{}`` means the
    route accepts nothing, which is the safe reading.  A misconfiguration
    here removes a capability; it never grants one.
    """
    try:
        raw = Path(os.path.expanduser(path)).read_text(encoding="utf-8")
    except OSError:
        return {}
    try:
        obj = json.loads(raw)
    except ValueError:
        return {}
    if not isinstance(obj, dict):
        return {}
    return {str(k): str(v) for k, v in obj.items()
            if isinstance(v, str) and v}


def sign(key: str, timestamp: str, body: bytes) -> str:
    """The signature both ends compute.  **One function, one definition.**

    The monitor's copy travels to a compute node as a standalone script, so
    the two halves ship separately and can only agree by being written
    against the same rule.  A change on one side would show up as reports
    that vanish silently -- the notifier swallows every failure by design,
    so an unreachable server never costs a run anything.

    The timestamp is inside the signed material rather than beside it:
    signing the body alone would leave the timestamp free to be rewritten.
    """
    msg = timestamp.encode("ascii", "replace") + b"." + body
    return hmac.new(key.encode("utf-8"), msg, hashlib.sha256).hexdigest()


def _resolve_user(presented: str, timestamp: str, body: bytes,
                  keys: Dict[str, str]) -> Optional[str]:
    """Which user's key produced ``presented``, or ``None``.

    Every key is tried and there is **no early exit** -- returning on the
    first match would make the time taken depend on a key's position in the
    file.  The loop is short and the cost is nothing; the property is worth
    holding by construction rather than by argument.

    The sender never states who it is: **the key is the claim.**  That is
    what stops one person's key writing into another's record, and what
    lets a key be revoked without disturbing anybody else.
    """
    found = None
    for user, key in keys.items():
        if hmac.compare_digest(presented, sign(key, timestamp, body)):
            found = user
    return found


def _logger_for(user: str) -> logging.Logger:
    """A rotating logger per user, made once and reused."""
    lg = _loggers.get(user)
    if lg is not None:
        return lg
    root = log_root()
    root.mkdir(parents=True, exist_ok=True)
    try:
        os.chmod(root, REPORT_DIR_MODE)
    except OSError:                                # pragma: no cover
        pass
    lg = logging.getLogger(f"molbuilder.notify.{user}")
    lg.propagate = False          # these are records, not app logs
    lg.setLevel(logging.INFO)
    handler = logging.handlers.RotatingFileHandler(
        root / f"{user}.jsonl", maxBytes=LOG_BYTES, backupCount=LOG_KEEP,
        encoding="utf-8")
    handler.setFormatter(logging.Formatter("%(message)s"))
    lg.addHandler(handler)
    # The file is created by the handler on first write, so tighten it
    # here AND after -- whichever exists first wins, and a mode set on a
    # file that is not there yet is not an error worth failing a report.
    try:
        os.chmod(root / f"{user}.jsonl", REPORT_MODE)
    except OSError:
        pass
    _loggers[user] = lg
    return lg


def _clean(payload: Dict[str, Any]) -> Dict[str, Any]:
    """The declared fields, as scalars, and nothing else.

    Everything here is attacker-controlled text once a key is known, and
    it ends up on a page.  Strings are length-capped and nested structures
    are dropped rather than flattened — a report has no use for them, and
    accepting one means deciding later how to render it.
    """
    out: Dict[str, Any] = {}
    for k in _FIELDS:
        v = payload.get(k)
        if isinstance(v, bool) or isinstance(v, (int, float)):
            out[k] = v
        elif isinstance(v, str):
            out[k] = v[:500]
    return out


#: How far out of step a report's clock may be, in seconds.  A signature
#: covers one body, so a replay can only ever duplicate a line in a capped
#: log -- this bounds how long a captured report stays replayable at all.
#: Generous, because a compute node's clock is not ours to trust closely
#: and a run that reports late is not a run that is lying.
MAX_SKEW_S = 15 * 60


def _deny() -> "NoReturn":
    """Every refusal, and they are all the same one.

    A 404 rendered by Flask's own router, so a wrong signature is
    byte-identical to a path that was never registered
    (`access-control.md` § 8 rule 2).  Still 4xx, so `rate_limit.py`
    counts it exactly as the old 401 was counted.

    **Every gate below depends on this RAISING.**  The call sites are bare
    ``_deny()`` statements, not ``return _deny()``, so if this ever stopped
    raising each one would fall through to the next step -- a wrong route
    would go on to be signature-checked, a bad signature would go on to be
    logged.  ``NoReturn`` says so to a reader and a type checker, and
    `test_notify_listener.py` holds it as a guard, because a comment is not
    a mechanism.
    """
    abort(404)
    raise AssertionError("unreachable: abort() raises")   # pragma: no cover


@bp.route("/api/<route>", methods=["POST"])
def api_notify(route: str):
    """Accept one run report.  Append it.  Say ``ok``.

    Everything that is not that answers :func:`_deny`.  There is no branch
    here that distinguishes *wrong segment* from *wrong signature* from
    *malformed body*, because telling them apart is the whole of what an
    attacker wants.
    """
    from flask import current_app

    if not hmac.compare_digest(route,
                               current_app.config["MB_NOTIFY_ROUTE"]):
        _deny()

    body = request.get_data(cache=False)
    if len(body) > MAX_BODY_BYTES:
        # Checked before parsing, so an oversized body is never read into
        # memory as JSON first.
        _deny()

    ts = request.headers.get("X-Molbuilder-Timestamp", "")
    sig = request.headers.get("X-Molbuilder-Signature", "")
    try:
        skew = abs(time.time() - float(ts))
    except (TypeError, ValueError):
        _deny()
    # NOT `if skew > MAX_SKEW_S`.  `float("nan")` parses, and EVERY
    # comparison against NaN is False -- so `nan > MAX_SKEW_S` is False and
    # a timestamp of "nan" walked straight through this gate.  Asking for
    # the good case instead means anything that is not a real, small number
    # is refused, NaN included.  (Found reviewing, 2026-08-27.  It needed a
    # valid signature over "nan" to exploit, so it was never an auth
    # bypass -- but a gate with a hole in it is not a gate.)
    if not skew <= MAX_SKEW_S:
        _deny()

    keys = read_keys(current_app.config["MB_NOTIFY_KEYS_FILE"])
    user = _resolve_user(sig, ts, body, keys)
    if user is None or not _SAFE_USER.match(user):
        # NOT marked as an auth challenge: see the module docstring.  A bad
        # signature is a probe and the limiter should hear about it.
        _deny()

    try:
        payload = json.loads(body.decode("utf-8", "replace") or "{}")
    except ValueError:
        _deny()
    if not isinstance(payload, dict):
        _deny()

    # THE VOLUME CAP, after the key is known so it can be per-key, and
    # answered as a 404 like every other refusal -- a different answer here
    # would say "this key is valid, you are merely early", which is exactly
    # what the other gates exist to withhold.
    if _too_many(user, time.time()):
        _deny()

    record = _clean(payload)
    # STAMPED BY US, not by the sender: the user this key belongs to, our
    # own clock, and the shape of the line.  `sent_at` (the sender's clock)
    # rides in the payload beside it, and when the two disagree that is
    # itself worth seeing.  The user is stamped rather than accepted --
    # there is no user field to send, so a key cannot write as somebody
    # else -- and it is IN the line as well as in the filename, because a
    # line pasted somewhere else must still say whose it is.
    record["v"] = SCHEMA
    record["user"] = user
    record["received_at"] = round(time.time(), 3)
    try:
        _logger_for(user).info(json.dumps(record))
    except OSError:
        # The log is the point, so a failure to write is worth an honest
        # 500 rather than an "ok" for a message nobody kept.  This one is
        # NOT a 404: it is our fault, not a claim about what exists.
        return jsonify({"ok": False, "error": "could not record"}), 500

    # Nothing about the payload comes back, and nothing stored is readable
    # through this route.  Reading is a logged-in browser's job.
    return jsonify({"ok": True})
